// Code generated by jzero. DO NOT EDIT.
package v1manageagent

import (
	"time"
)

var (
	_ = time.Now()
)

type AccountStatus struct {
	AuthMode string `json:"authMode,optional"`
	Email    string `json:"email,optional"`
	PlanType string `json:"planType,optional"`
	LoggedIn bool   `json:"loggedIn"`
}

type DeleteSkillRequest struct {
	SkillName string `path:"skill_name" validate:"required"`
}

type DeleteSkillResponse struct {
}

type DeleteUserTokenQuotaRequest struct {
	UserUuid string `path:"user_uuid" validate:"required"`
}

type DeleteUserTokenQuotaResponse struct {
}

type GetAccountStatusRequest struct {
}

type GetAccountStatusResponse struct {
	Account AccountStatus `json:"account"`
}

type GetSettingsRequest struct {
}

type GetSettingsResponse struct {
	ActiveProvider  string          `json:"activeProvider"`
	Model           string          `json:"model"`
	ReasoningEffort string          `json:"reasoningEffort"`
	Providers       []ModelProvider `json:"providers"`
	Account         AccountStatus   `json:"account"`
	Runtime         RuntimeStatus   `json:"runtime"`
}

type GetTokenQuotaGlobalRequest struct {
}

type GetTokenQuotaGlobalResponse struct {
	Quota TokenQuotaGlobal `json:"quota"`
}

type GetUserTokenQuotaRequest struct {
	UserUuid string `path:"user_uuid" validate:"required"`
}

type GetUserTokenQuotaResponse struct {
	Quota TokenQuotaUser `json:"quota"`
}

type HomeOverviewRequest struct {
}

type HomeOverviewResponse struct {
	AgentRunning   bool   `json:"agentRunning"`
	ActiveProvider string `json:"activeProvider"`
	Model          string `json:"model"`
	ModelName      string `json:"modelName"`
	TotalTokens    int64  `json:"totalTokens"`
	SkillCount     int64  `json:"skillCount"`
}

type ListSkillsRequest struct {
}

type ListSkillsResponse struct {
	Skills []Skill `json:"skills"`
}

type LoginApiKeyRequest struct {
	ApiKey string `json:"apiKey" validate:"required"`
}

type LoginApiKeyResponse struct {
	Account AccountStatus `json:"account"`
}

type LogoutRequest struct {
}

type LogoutResponse struct {
}

type ModelProvider struct {
	Id        string          `json:"id"`
	Name      string          `json:"name"`
	BaseUrl   string          `json:"baseUrl,optional"`
	WireApi   string          `json:"wireApi"`
	HasApiKey bool            `json:"hasApiKey"`
	Models    []ProviderModel `json:"models"`
}

type ProviderModel struct {
	Id                     string   `json:"id"`
	Name                   string   `json:"name"`
	DefaultReasoningEffort string   `json:"defaultReasoningEffort,optional"`
	ReasoningEfforts       []string `json:"reasoningEfforts"`
}

type ResetUserTokenQuotaRequest struct {
	UserUuid string `path:"user_uuid" validate:"required"`
}

type ResetUserTokenQuotaResponse struct {
}

type RuntimeStatus struct {
	Running bool `json:"running"`
}

type SaveProviderApiKeyRequest struct {
	ProviderId string `json:"providerId" validate:"required"`
	ApiKey     string `json:"apiKey" validate:"required"`
}

type SaveProviderApiKeyResponse struct {
	HasApiKey bool `json:"hasApiKey"`
}

type SaveSelectionRequest struct {
	ProviderId      string `json:"providerId" validate:"required"`
	Model           string `json:"model" validate:"required"`
	ReasoningEffort string `json:"reasoningEffort,optional"`
}

type SaveSelectionResponse struct {
}

type SaveTokenQuotaGlobalRequest struct {
	FiveHourLimitTokens int64 `json:"fiveHourLimitTokens" validate:"required,gt=0"`
	SevenDayLimitTokens int64 `json:"sevenDayLimitTokens" validate:"required,gt=0"`
}

type SaveTokenQuotaGlobalResponse struct {
}

type SaveUserTokenQuotaRequest struct {
	UserUuid            string `path:"user_uuid" validate:"required"`
	Enabled             bool   `json:"enabled"`
	FiveHourDisabled    bool   `json:"fiveHourDisabled"`
	FiveHourLimitTokens *int64 `json:"fiveHourLimitTokens,optional" validate:"omitempty,gt=0"`
	SevenDayLimitTokens *int64 `json:"sevenDayLimitTokens,optional" validate:"omitempty,gt=0"`
}

type SaveUserTokenQuotaResponse struct {
}

type Skill struct {
	Name string `json:"name"`
}

type SkillDetailRequest struct {
	SkillName string `path:"skill_name" validate:"required"`
	File      string `form:"file,optional"`
}

type SkillDetailResponse struct {
	Skill       Skill       `json:"skill"`
	Files       []SkillFile `json:"files"`
	CurrentFile string      `json:"currentFile"`
	Content     string      `json:"content"`
}

type SkillFile struct {
	Name     string      `json:"name"`
	Path     string      `json:"path"`
	Type     string      `json:"type,options=file|directory"`
	Children []SkillFile `json:"children,optional"`
}

type StartChatGPTLoginRequest struct {
}

type StartChatGPTLoginResponse struct {
	LoginId         string `json:"loginId"`
	VerificationUrl string `json:"verificationUrl"`
	UserCode        string `json:"userCode"`
	ExpiresIn       int64  `json:"expiresIn,optional"`
}

type TokenQuotaGlobal struct {
	FiveHourLimitTokens int64 `json:"fiveHourLimitTokens"`
	SevenDayLimitTokens int64 `json:"sevenDayLimitTokens"`
}

type TokenQuotaUser struct {
	UserUuid               string  `json:"userUuid"`
	Configured             bool    `json:"configured"`
	Enabled                bool    `json:"enabled"`
	FiveHourDisabled       bool    `json:"fiveHourDisabled"`
	FiveHourLimitTokens    *int64  `json:"fiveHourLimitTokens,omitempty"`
	SevenDayLimitTokens    *int64  `json:"sevenDayLimitTokens,omitempty"`
	EffectiveFiveHourLimit *int64  `json:"effectiveFiveHourLimit,omitempty"`
	EffectiveSevenDayLimit int64   `json:"effectiveSevenDayLimit"`
	FiveHourUsedTokens     int64   `json:"fiveHourUsedTokens"`
	SevenDayUsedTokens     int64   `json:"sevenDayUsedTokens"`
	FiveHourResetAt        *string `json:"fiveHourResetAt,omitempty"`
	SevenDayResetAt        *string `json:"sevenDayResetAt,omitempty"`
	QuotaResetAt           *string `json:"quotaResetAt,omitempty"`
}

type UpdateSkillFileRequest struct {
	SkillName string `path:"skill_name" validate:"required"`
	File      string `json:"file" validate:"required"`
	Content   string `json:"content"`
}

type UpdateSkillFileResponse struct {
}

type UploadSkillRequest struct {
}

type UploadSkillResponse struct {
	Name string `json:"name"`
}
