// Code generated by jzero. DO NOT EDIT.
package v1manageagent

import (
	"time"
)

var (
	_ = time.Now()
)

type DeleteSkillRequest struct {
	SkillName string `path:"skill_name" validate:"required"`
}

type DeleteSkillResponse struct {
}

type ListSkillsRequest struct {
}

type ListSkillsResponse struct {
	Skills []Skill `json:"skills"`
}

type Skill struct {
	Name string `json:"name"`
}

type SkillDetailRequest struct {
	SkillName string `path:"skill_name" validate:"required"`
	File      string `form:"file,optional"`
}

type SkillDetailResponse struct {
	Skill       Skill       `json:"skill"`
	Files       []SkillFile `json:"files"`
	CurrentFile string      `json:"currentFile"`
	Content     string      `json:"content"`
}

type SkillFile struct {
	Name     string      `json:"name"`
	Path     string      `json:"path"`
	Type     string      `json:"type,options=file|directory"`
	Children []SkillFile `json:"children,optional"`
}

type UpdateSkillFileRequest struct {
	SkillName string `path:"skill_name" validate:"required"`
	File      string `json:"file" validate:"required"`
	Content   string `json:"content"`
}

type UpdateSkillFileResponse struct {
}

type UploadSkillRequest struct {
}

type UploadSkillResponse struct {
	Name string `json:"name"`
}
