// Code generated by jzero. DO NOT EDIT.
package v1home

import (
	"time"
)

var (
	_ = time.Now()
)

type HomeOverviewRequest struct {
}

type HomeOverviewResponse struct {
	AgentRunning   bool   `json:"agentRunning"`
	ActiveProvider string `json:"activeProvider"`
	Model          string `json:"model"`
	ModelName      string `json:"modelName"`
	TotalTokens    int64  `json:"totalTokens"`
	SkillCount     int64  `json:"skillCount"`
}
