// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	{{if .Plugins}}"github.com/zeromicro/go-zero/core/logx"{{end}}
	"github.com/zeromicro/go-zero/rest"

    "{{ .Module }}/internal/handler"
    "{{ .Module }}/internal/svc"
	{{range $i, $v := .Plugins}}serverless{{ $i }} "{{ $v.Module }}/serverless"
	{{end}}
)

func LoadPlugins(server *rest.Server, svcCtx *svc.ServiceContext) {
	{{ range $i, $v := .Plugins }}
	{
        serverless := serverless{{ $i }}.New(svcCtx.ServiceContext)
        if err := svcCtx.PluginRegistry.RegisterProvider("{{ $v.Name }}", serverless); err != nil {
            logx.Errorf("register plugin %q locale provider: %v", "{{ $v.Name }}", err)
        }
        serverless.HandlerFunc(server, serverless.SvcCtx)
        handler.RegisterRoute2Code(serverless.RouteCodesMap)
    }
	{{end}}
}
