// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package agent_character

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	agentCharacterFieldNames               []string
	agentCharacterRows                     string
	agentCharacterRowsExpectAutoFieldNames []string
	agentCharacterRowsExpectAutoSet        string
)

const (
	Uuid        condition.Field = "uuid"
	UserUuid    condition.Field = "user_uuid"
	Name        condition.Field = "name"
	Description condition.Field = "description"
	Prompt      condition.Field = "prompt"
	IsBuiltin   condition.Field = "is_builtin"
	Sort        condition.Field = "sort"
	CreateTime  condition.Field = "create_time"
	UpdateTime  condition.Field = "update_time"
)

func initAgentCharacterVars(flavor sqlbuilder.Flavor) {
	agentCharacterFieldNames = condition.RawFieldNamesWithFlavor(flavor, &AgentCharacter{})
	agentCharacterRows = strings.Join(agentCharacterFieldNames, ",")
	agentCharacterRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, agentCharacterFieldNames, "create_time", "update_time")
	agentCharacterRowsExpectAutoSet = strings.Join(agentCharacterRowsExpectAutoFieldNames, ",")
}

type (
	agentCharacterModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *AgentCharacter) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *AgentCharacter) error
		FindOne(ctx context.Context, session sqlx.Session, uuid string) (*AgentCharacter, error)
		FindOneByName(ctx context.Context, session sqlx.Session, name string) (*AgentCharacter, error)
		FindOneByUserUuidName(ctx context.Context, session sqlx.Session, userUuid sql.NullString, name string) (*AgentCharacter, error)
		Update(ctx context.Context, session sqlx.Session, data *AgentCharacter) error
		Delete(ctx context.Context, session sqlx.Session, uuid string) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) agentCharacterModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*AgentCharacter) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentCharacter, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*AgentCharacter, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*AgentCharacter, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*AgentCharacter, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*AgentCharacter, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentCharacter, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultAgentCharacterModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	AgentCharacter struct {
		Uuid        string         `db:"uuid"`
		UserUuid    sql.NullString `db:"user_uuid"`
		Name        string         `db:"name"`
		Description string         `db:"description"`
		Prompt      string         `db:"prompt"`
		IsBuiltin   bool           `db:"is_builtin"`
		Sort        int64          `db:"sort"`
		CreateTime  time.Time      `db:"create_time"`
		UpdateTime  time.Time      `db:"update_time"`
	}
)

func newAgentCharacterModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultAgentCharacterModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initAgentCharacterVars(o.Flavor)

	return &defaultAgentCharacterModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "agent_character"),
	}
}

// NewOriginalAgentCharacterModel returns a original model for the database table.
func NewOriginalAgentCharacterModel(conn sqlx.SqlConn) AgentCharacterModel {
	return &customAgentCharacterModel{
		defaultAgentCharacterModel: newAgentCharacterModel(conn),
	}
}

func (m *defaultAgentCharacterModel) clone() *defaultAgentCharacterModel {
	return &defaultAgentCharacterModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultAgentCharacterModel) Delete(ctx context.Context, session sqlx.Session, uuid string) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "uuid"), uuid))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentCharacterModel) FindOne(ctx context.Context, session sqlx.Session, uuid string) (*AgentCharacter, error) {
	sb := sqlbuilder.Select(agentCharacterRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "uuid"), uuid))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp AgentCharacter
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentCharacterModel) FindOneByName(ctx context.Context, session sqlx.Session, name string) (*AgentCharacter, error) {
	var resp AgentCharacter
	var err error

	sb := sqlbuilder.Select(agentCharacterRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "name = $1", name)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentCharacterModel) FindOneByUserUuidName(ctx context.Context, session sqlx.Session, userUuid sql.NullString, name string) (*AgentCharacter, error) {
	var resp AgentCharacter
	var err error

	sb := sqlbuilder.Select(agentCharacterRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "user_uuid = $1 and name = $2", userUuid, name)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentCharacterModel) Insert(ctx context.Context, session sqlx.Session, data *AgentCharacter) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(agentCharacterRowsExpectAutoSet).
		Values(data.Uuid, data.UserUuid, data.Name, data.Description, data.Prompt, data.IsBuiltin, data.Sort).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultAgentCharacterModel) InsertV2(ctx context.Context, session sqlx.Session, data *AgentCharacter) error {
	var statement string
	var args []any
	statement, args = sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(agentCharacterRowsExpectAutoSet).
		Values(data.Uuid, data.UserUuid, data.Name, data.Description, data.Prompt, data.IsBuiltin, data.Sort).BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentCharacterModel) Update(ctx context.Context, session sqlx.Session, data *AgentCharacter) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "user_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "user_uuid"), data.UserUuid))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "name")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "name"), data.Name))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "description")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "description"), data.Description))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "prompt")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "prompt"), data.Prompt))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "is_builtin")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "is_builtin"), data.IsBuiltin))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "sort")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "sort"), data.Sort))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}
	if slices.Contains(agentCharacterRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "update_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "update_time"), data.UpdateTime))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentCharacterModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customAgentCharacterModel) WithTable(f func(table string) string) agentCharacterModel {
	mc := &customAgentCharacterModel{
		defaultAgentCharacterModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customAgentCharacterModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*AgentCharacter) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(agentCharacterRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Uuid, data.UserUuid, data.Name, data.Description, data.Prompt, data.IsBuiltin, data.Sort)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customAgentCharacterModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*AgentCharacter, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(agentCharacterFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*AgentCharacter
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customAgentCharacterModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*AgentCharacter, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customAgentCharacterModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentCharacter, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, agentCharacterFieldNames, conditions...)
}

func (m *customAgentCharacterModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customAgentCharacterModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*AgentCharacter, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(agentCharacterFieldNames), conditions...)
}

func (m *customAgentCharacterModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*AgentCharacter, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(agentCharacterFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp AgentCharacter
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customAgentCharacterModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentCharacter, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(agentCharacterFieldNames...)...).From(m.table), conditions...)

	var resp []*AgentCharacter
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customAgentCharacterModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customAgentCharacterModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
