// Code generated by jzero. DO NOT EDIT.
package v1managecharacter

import (
	"time"
)

var (
	_ = time.Now()
)

type Character struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Prompt      string `json:"prompt"`
	Builtin     bool   `json:"builtin"`
	Sort        int64  `json:"sort"`
	Owner       *Owner `json:"owner,omitempty"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type CreateRequest struct {
	Name        string `json:"name" validate:"required,max=80"`
	Description string `json:"description,optional" validate:"max=240"`
	Prompt      string `json:"prompt" validate:"required,max=16000"`
	Sort        int64  `json:"sort,default=0"`
}

type DeleteRequest struct {
	CharacterId string `path:"character_id" validate:"required"`
}

type DeleteResponse struct {
}

type ListRequest struct {
	PageRequest
	Kind    string `form:"kind" validate:"required,oneof=builtin custom"`
	Keyword string `form:"keyword,optional"`
}

type ListResponse struct {
	PageResponse
	Records []Character `json:"records"`
}

type Owner struct {
	UserUuid  string `json:"userUuid"`
	Username  string `json:"username"`
	NickName  string `json:"nickName"`
	UserEmail string `json:"userEmail"`
}

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}

type PageResponse struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}

type UpdateRequest struct {
	CharacterId string `path:"character_id" validate:"required"`
	Name        string `json:"name" validate:"required,max=80"`
	Description string `json:"description,optional" validate:"max=240"`
	Prompt      string `json:"prompt" validate:"required,max=16000"`
	Sort        int64  `json:"sort,default=0"`
}
