// Code generated by jzero. DO NOT EDIT.
package v1agentconversation

import (
	"time"
)

var (
	_ = time.Now()
)

type CancelTurnResponse struct {
}

type Conversation struct {
	Id               string  `json:"id"`
	Title            string  `json:"title"`
	Status           string  `json:"status"`
	PinnedAt         *string `json:"pinnedAt,omitempty"`
	ArchivedAt       *string `json:"archivedAt,omitempty"`
	GroupId          *string `json:"groupId,omitempty"`
	Running          bool    `json:"running"`
	RunningStartedAt *string `json:"runningStartedAt,omitempty"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
}

type CreateRequest struct {
	GroupId *string `json:"groupId,optional"`
}

type DeleteResponse struct {
}

type DetailResponse struct {
	Conversation   Conversation `json:"conversation"`
	StreamPosition string       `json:"streamPosition"`
	Turns          []Turn       `json:"turns"`
}

type EventsRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
}

type EventsResponse struct {
	Event string `json:"event"`
	Data  string `json:"data"`
}

type GeneratedImage struct {
	Id      string `json:"id"`
	DataUrl string `json:"dataUrl"`
	Alt     string `json:"alt"`
}

type ListResponse struct {
	Conversations []Conversation `json:"conversations"`
}

type MessageAttachment struct {
	Name        string `json:"name"`
	Path        string `json:"path"`
	ContentType string `json:"contentType"`
	Size        int64  `json:"size"`
	Kind        string `json:"kind"`
}

type MessageAttachmentRef struct {
	Path string `json:"path" validate:"required"`
}

type MetadataResponse struct {
	Id                string `json:"id"`
	Title             string `json:"title"`
	WorkspaceDir      string `json:"workspaceDir"`
	GeneratedImageDir string `json:"generatedImageDir"`
	UpdatedAt         string `json:"updatedAt"`
}

type PathRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
}

type SendMessageRequest struct {
	ConversationId string                 `path:"conversation_id" validate:"required"`
	Content        string                 `json:"content,optional"`
	Attachments    []MessageAttachmentRef `json:"attachments,optional"`
}

type StartedTurn struct {
	Id        string `json:"id"`
	StartedAt string `json:"startedAt"`
}

type StatsResponse struct {
	TotalConversations    int64 `json:"totalConversations"`
	ActiveConversations   int64 `json:"activeConversations"`
	RunningConversations  int64 `json:"runningConversations"`
	ArchivedConversations int64 `json:"archivedConversations"`
	TotalTokens           int64 `json:"totalTokens"`
	TokenUsageAvailable   bool  `json:"tokenUsageAvailable"`
}

type Turn struct {
	Id          string                   `json:"id"`
	Status      string                   `json:"status"`
	StartedAt   *string                  `json:"startedAt,omitempty"`
	CompletedAt *string                  `json:"completedAt,omitempty"`
	DurationMs  *int64                   `json:"durationMs,omitempty"`
	Error       string                   `json:"error,omitempty"`
	Items       []map[string]interface{} `json:"items"`
}

type UpdateRequest struct {
	ConversationId string  `path:"conversation_id" validate:"required"`
	Title          *string `json:"title,optional"`
	Pinned         *bool   `json:"pinned,optional"`
	Archived       *bool   `json:"archived,optional"`
	GroupId        *string `json:"groupId,optional"`
}

type UploadAttachmentRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
}

type UploadAttachmentResponse struct {
	Attachment MessageAttachment `json:"attachment"`
}

type WorkspaceEntry struct {
	Name     string           `json:"name"`
	Path     string           `json:"path"`
	Type     string           `json:"type"`
	Children []WorkspaceEntry `json:"children"`
}

type WorkspaceFileRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
	FilePath       string `form:"path" validate:"required"`
}

type WorkspaceFilesResponse struct {
	Files []WorkspaceEntry `json:"files"`
}
