// Code generated by jzero. DO NOT EDIT.
package v1manageemail

import (
	"time"
)

var (
	_ = time.Now()
)

type EmailConfig struct {
	From        string `json:"from"`
	Host        string `json:"host"`
	Port        int64  `json:"port"`
	Username    string `json:"username"`
	EnableSsl   bool   `json:"enableSsl"`
	IsVerify    bool   `json:"isVerify"`
	HasPassword bool   `json:"hasPassword"`
}

type GetConfigRequest struct {
}

type GetConfigResponse struct {
	Configured bool        `json:"configured"`
	Config     EmailConfig `json:"config"`
}

type SaveConfigRequest struct {
	From      string `json:"from" validate:"required,email"`
	Host      string `json:"host" validate:"required"`
	Port      int64  `json:"port" validate:"required,gte=1,lte=65535"`
	Username  string `json:"username" validate:"required"`
	Password  string `json:"password,optional"`
	EnableSsl bool   `json:"enableSsl"`
	IsVerify  bool   `json:"isVerify"`
}

type SaveConfigResponse struct {
}

type TestConfigRequest struct {
	Recipient string `json:"recipient" validate:"required,email"`
}

type TestConfigResponse struct {
}
