// Code generated by jzero. DO NOT EDIT.
package v1authapikey

import (
	"time"
)

var (
	_ = time.Now()
)

type ApiKey struct {
	Id        string `json:"id"`
	KeyHint   string `json:"keyHint"`
	CreatedAt string `json:"createdAt"`
}

type CreateResponse struct {
	ApiKey
	Key string `json:"key"`
}

type DeleteRequest struct {
	Id string `path:"id" validate:"required"`
}

type DeleteResponse struct {
}

type ListResponse struct {
	Keys []ApiKey `json:"keys"`
}
