// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package agent_api_key

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	agentApiKeyFieldNames               []string
	agentApiKeyRows                     string
	agentApiKeyRowsExpectAutoFieldNames []string
	agentApiKeyRowsExpectAutoSet        string
)

const (
	Uuid       condition.Field = "uuid"
	UserUuid   condition.Field = "user_uuid"
	KeyHash    condition.Field = "key_hash"
	KeyHint    condition.Field = "key_hint"
	CreateTime condition.Field = "create_time"
)

func initAgentApiKeyVars(flavor sqlbuilder.Flavor) {
	agentApiKeyFieldNames = condition.RawFieldNamesWithFlavor(flavor, &AgentApiKey{})
	agentApiKeyRows = strings.Join(agentApiKeyFieldNames, ",")
	agentApiKeyRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, agentApiKeyFieldNames, "create_time", "update_time")
	agentApiKeyRowsExpectAutoSet = strings.Join(agentApiKeyRowsExpectAutoFieldNames, ",")
}

type (
	agentApiKeyModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *AgentApiKey) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *AgentApiKey) error
		FindOne(ctx context.Context, session sqlx.Session, uuid string) (*AgentApiKey, error)
		FindOneByKeyHash(ctx context.Context, session sqlx.Session, keyHash string) (*AgentApiKey, error)
		Update(ctx context.Context, session sqlx.Session, data *AgentApiKey) error
		Delete(ctx context.Context, session sqlx.Session, uuid string) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) agentApiKeyModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*AgentApiKey) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentApiKey, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*AgentApiKey, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*AgentApiKey, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*AgentApiKey, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*AgentApiKey, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentApiKey, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultAgentApiKeyModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	AgentApiKey struct {
		Uuid       string    `db:"uuid"`
		UserUuid   string    `db:"user_uuid"`
		KeyHash    string    `db:"key_hash"`
		KeyHint    string    `db:"key_hint"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newAgentApiKeyModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultAgentApiKeyModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initAgentApiKeyVars(o.Flavor)

	return &defaultAgentApiKeyModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "agent_api_key"),
	}
}

// NewOriginalAgentApiKeyModel returns a original model for the database table.
func NewOriginalAgentApiKeyModel(conn sqlx.SqlConn) AgentApiKeyModel {
	return &customAgentApiKeyModel{
		defaultAgentApiKeyModel: newAgentApiKeyModel(conn),
	}
}

func (m *defaultAgentApiKeyModel) clone() *defaultAgentApiKeyModel {
	return &defaultAgentApiKeyModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultAgentApiKeyModel) Delete(ctx context.Context, session sqlx.Session, uuid string) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "uuid"), uuid))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentApiKeyModel) FindOne(ctx context.Context, session sqlx.Session, uuid string) (*AgentApiKey, error) {
	sb := sqlbuilder.Select(agentApiKeyRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "uuid"), uuid))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp AgentApiKey
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentApiKeyModel) FindOneByKeyHash(ctx context.Context, session sqlx.Session, keyHash string) (*AgentApiKey, error) {
	var resp AgentApiKey
	var err error

	sb := sqlbuilder.Select(agentApiKeyRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "key_hash = $1", keyHash)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentApiKeyModel) Insert(ctx context.Context, session sqlx.Session, data *AgentApiKey) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(agentApiKeyRowsExpectAutoSet).
		Values(data.Uuid, data.UserUuid, data.KeyHash, data.KeyHint).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultAgentApiKeyModel) InsertV2(ctx context.Context, session sqlx.Session, data *AgentApiKey) error {
	var statement string
	var args []any
	statement, args = sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(agentApiKeyRowsExpectAutoSet).
		Values(data.Uuid, data.UserUuid, data.KeyHash, data.KeyHint).BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentApiKeyModel) Update(ctx context.Context, session sqlx.Session, data *AgentApiKey) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(agentApiKeyRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	}
	if slices.Contains(agentApiKeyRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "user_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "user_uuid"), data.UserUuid))
	}
	if slices.Contains(agentApiKeyRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "key_hash")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "key_hash"), data.KeyHash))
	}
	if slices.Contains(agentApiKeyRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "key_hint")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "key_hint"), data.KeyHint))
	}
	if slices.Contains(agentApiKeyRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentApiKeyModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customAgentApiKeyModel) WithTable(f func(table string) string) agentApiKeyModel {
	mc := &customAgentApiKeyModel{
		defaultAgentApiKeyModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customAgentApiKeyModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*AgentApiKey) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(agentApiKeyRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Uuid, data.UserUuid, data.KeyHash, data.KeyHint)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customAgentApiKeyModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*AgentApiKey, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(agentApiKeyFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*AgentApiKey
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customAgentApiKeyModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*AgentApiKey, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customAgentApiKeyModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentApiKey, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, agentApiKeyFieldNames, conditions...)
}

func (m *customAgentApiKeyModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customAgentApiKeyModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*AgentApiKey, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(agentApiKeyFieldNames), conditions...)
}

func (m *customAgentApiKeyModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*AgentApiKey, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(agentApiKeyFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp AgentApiKey
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customAgentApiKeyModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentApiKey, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(agentApiKeyFieldNames...)...).From(m.table), conditions...)

	var resp []*AgentApiKey
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customAgentApiKeyModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customAgentApiKeyModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
