hooks:
  before:
    - go install tool

migrate:
  driver: pgx
  datasource-url: "postgres://root:123456@127.0.0.1:5432/agentrazor?sslmode=disable"
  source-append-driver: true

gen:
  hooks:
    after:
      - jzero gen swagger

  style: go_zero
  git-change: true
  route2Code: true

  model-driver: pgx
  model-cache: false
  model-ignore-columns: ["create_time", "update_time"]
  model-datasource: true
  model-datasource-url: "postgres://root:123456@127.0.0.1:5432/agentrazor?sslmode=disable"
  model-datasource-table:
    - agent_api_key
    - conversation
    - conversation_group
    - conversation_token_usage_event
    - manage_email
    - manage_menu
    - manage_role
    - manage_role_menu
    - manage_user
    - manage_user_role
  model-schema: public
