// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package conversation

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	conversationFieldNames               []string
	conversationRows                     string
	conversationRowsExpectAutoFieldNames []string
	conversationRowsExpectAutoSet        string
)

const (
	Id        condition.Field = "id"
	UserUuid  condition.Field = "user_uuid"
	GroupUuid condition.Field = "group_uuid"
	CreatedAt condition.Field = "created_at"
)

func initConversationVars(flavor sqlbuilder.Flavor) {
	conversationFieldNames = condition.RawFieldNamesWithFlavor(flavor, &Conversation{})
	conversationRows = strings.Join(conversationFieldNames, ",")
	conversationRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, conversationFieldNames, "`create_time`", "`update_time`")
	conversationRowsExpectAutoSet = strings.Join(conversationRowsExpectAutoFieldNames, ",")
}

type (
	conversationModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *Conversation) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *Conversation) error
		FindOne(ctx context.Context, session sqlx.Session, id string) (*Conversation, error)
		Update(ctx context.Context, session sqlx.Session, data *Conversation) error
		Delete(ctx context.Context, session sqlx.Session, id string) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) conversationModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*Conversation) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Conversation, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*Conversation, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*Conversation, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*Conversation, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*Conversation, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Conversation, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultConversationModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	Conversation struct {
		Id        string         `db:"id"`
		UserUuid  string         `db:"user_uuid"`
		GroupUuid sql.NullString `db:"group_uuid"`
		CreatedAt time.Time      `db:"created_at"`
	}
)

func newConversationModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultConversationModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initConversationVars(o.Flavor)

	return &defaultConversationModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "conversation"),
	}
}

// NewOriginalConversationModel returns a original model for the database table.
func NewOriginalConversationModel(conn sqlx.SqlConn) ConversationModel {
	return &customConversationModel{
		defaultConversationModel: newConversationModel(conn),
	}
}

func (m *defaultConversationModel) clone() *defaultConversationModel {
	return &defaultConversationModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultConversationModel) Delete(ctx context.Context, session sqlx.Session, id string) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationModel) FindOne(ctx context.Context, session sqlx.Session, id string) (*Conversation, error) {
	sb := sqlbuilder.Select(conversationRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp Conversation
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationModel) Insert(ctx context.Context, session sqlx.Session, data *Conversation) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(conversationRowsExpectAutoSet).
		Values(data.Id, data.UserUuid, data.GroupUuid, data.CreatedAt).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultConversationModel) InsertV2(ctx context.Context, session sqlx.Session, data *Conversation) error {
	var statement string
	var args []any
	statement, args = sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(conversationRowsExpectAutoSet).
		Values(data.Id, data.UserUuid, data.GroupUuid, data.CreatedAt).BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationModel) Update(ctx context.Context, session sqlx.Session, data *Conversation) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(conversationRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	}
	if slices.Contains(conversationRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "user_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "user_uuid"), data.UserUuid))
	}
	if slices.Contains(conversationRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "group_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "group_uuid"), data.GroupUuid))
	}
	if slices.Contains(conversationRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "created_at")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "created_at"), data.CreatedAt))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), data.Id))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customConversationModel) WithTable(f func(table string) string) conversationModel {
	mc := &customConversationModel{
		defaultConversationModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customConversationModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*Conversation) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(conversationRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Id, data.UserUuid, data.GroupUuid, data.CreatedAt)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customConversationModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*Conversation, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(conversationFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*Conversation
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customConversationModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*Conversation, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customConversationModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Conversation, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, conversationFieldNames, conditions...)
}

func (m *customConversationModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customConversationModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*Conversation, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(conversationFieldNames), conditions...)
}

func (m *customConversationModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*Conversation, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(conversationFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp Conversation
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customConversationModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Conversation, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(conversationFieldNames...)...).From(m.table), conditions...)

	var resp []*Conversation
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customConversationModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customConversationModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
