// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package conversation_token_usage_event

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	conversationTokenUsageEventFieldNames               []string
	conversationTokenUsageEventRows                     string
	conversationTokenUsageEventRowsExpectAutoFieldNames []string
	conversationTokenUsageEventRowsExpectAutoSet        string
)

const (
	Id                         condition.Field = "id"
	ConversationId             condition.Field = "conversation_id"
	UserUuid                   condition.Field = "user_uuid"
	TurnId                     condition.Field = "turn_id"
	LastInputTokens            condition.Field = "last_input_tokens"
	LastCachedInputTokens      condition.Field = "last_cached_input_tokens"
	LastCacheWriteInputTokens  condition.Field = "last_cache_write_input_tokens"
	LastOutputTokens           condition.Field = "last_output_tokens"
	LastReasoningOutputTokens  condition.Field = "last_reasoning_output_tokens"
	LastTotalTokens            condition.Field = "last_total_tokens"
	TotalInputTokens           condition.Field = "total_input_tokens"
	TotalCachedInputTokens     condition.Field = "total_cached_input_tokens"
	TotalCacheWriteInputTokens condition.Field = "total_cache_write_input_tokens"
	TotalOutputTokens          condition.Field = "total_output_tokens"
	TotalReasoningOutputTokens condition.Field = "total_reasoning_output_tokens"
	TotalTokens                condition.Field = "total_tokens"
	ModelContextWindow         condition.Field = "model_context_window"
	CreateTime                 condition.Field = "create_time"
)

func initConversationTokenUsageEventVars(flavor sqlbuilder.Flavor) {
	conversationTokenUsageEventFieldNames = condition.RawFieldNamesWithFlavor(flavor, &ConversationTokenUsageEvent{})
	conversationTokenUsageEventRows = strings.Join(conversationTokenUsageEventFieldNames, ",")
	conversationTokenUsageEventRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, conversationTokenUsageEventFieldNames, "id", "create_time", "update_time")
	conversationTokenUsageEventRowsExpectAutoSet = strings.Join(conversationTokenUsageEventRowsExpectAutoFieldNames, ",")
}

type (
	conversationTokenUsageEventModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *ConversationTokenUsageEvent) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *ConversationTokenUsageEvent) error
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*ConversationTokenUsageEvent, error)
		Update(ctx context.Context, session sqlx.Session, data *ConversationTokenUsageEvent) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) conversationTokenUsageEventModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*ConversationTokenUsageEvent) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ConversationTokenUsageEvent, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ConversationTokenUsageEvent, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultConversationTokenUsageEventModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	ConversationTokenUsageEvent struct {
		Id                         int64         `db:"id"`
		ConversationId             string        `db:"conversation_id"`
		UserUuid                   string        `db:"user_uuid"`
		TurnId                     string        `db:"turn_id"`
		LastInputTokens            int64         `db:"last_input_tokens"`
		LastCachedInputTokens      int64         `db:"last_cached_input_tokens"`
		LastCacheWriteInputTokens  int64         `db:"last_cache_write_input_tokens"`
		LastOutputTokens           int64         `db:"last_output_tokens"`
		LastReasoningOutputTokens  int64         `db:"last_reasoning_output_tokens"`
		LastTotalTokens            int64         `db:"last_total_tokens"`
		TotalInputTokens           int64         `db:"total_input_tokens"`
		TotalCachedInputTokens     int64         `db:"total_cached_input_tokens"`
		TotalCacheWriteInputTokens int64         `db:"total_cache_write_input_tokens"`
		TotalOutputTokens          int64         `db:"total_output_tokens"`
		TotalReasoningOutputTokens int64         `db:"total_reasoning_output_tokens"`
		TotalTokens                int64         `db:"total_tokens"`
		ModelContextWindow         sql.NullInt64 `db:"model_context_window"`
		CreateTime                 time.Time     `db:"create_time"`
	}
)

func newConversationTokenUsageEventModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultConversationTokenUsageEventModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initConversationTokenUsageEventVars(o.Flavor)

	return &defaultConversationTokenUsageEventModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "conversation_token_usage_event"),
	}
}

// NewOriginalConversationTokenUsageEventModel returns a original model for the database table.
func NewOriginalConversationTokenUsageEventModel(conn sqlx.SqlConn) ConversationTokenUsageEventModel {
	return &customConversationTokenUsageEventModel{
		defaultConversationTokenUsageEventModel: newConversationTokenUsageEventModel(conn),
	}
}

func (m *defaultConversationTokenUsageEventModel) clone() *defaultConversationTokenUsageEventModel {
	return &defaultConversationTokenUsageEventModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultConversationTokenUsageEventModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "id"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationTokenUsageEventModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*ConversationTokenUsageEvent, error) {
	sb := sqlbuilder.Select(conversationTokenUsageEventRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "id"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp ConversationTokenUsageEvent
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationTokenUsageEventModel) Insert(ctx context.Context, session sqlx.Session, data *ConversationTokenUsageEvent) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(conversationTokenUsageEventRowsExpectAutoSet).
		Values(data.ConversationId, data.UserUuid, data.TurnId, data.LastInputTokens, data.LastCachedInputTokens, data.LastCacheWriteInputTokens, data.LastOutputTokens, data.LastReasoningOutputTokens, data.LastTotalTokens, data.TotalInputTokens, data.TotalCachedInputTokens, data.TotalCacheWriteInputTokens, data.TotalOutputTokens, data.TotalReasoningOutputTokens, data.TotalTokens, data.ModelContextWindow).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultConversationTokenUsageEventModel) InsertV2(ctx context.Context, session sqlx.Session, data *ConversationTokenUsageEvent) error {
	var statement string
	var args []any
	if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(conversationTokenUsageEventRowsExpectAutoSet).
			Values(data.ConversationId, data.UserUuid, data.TurnId, data.LastInputTokens, data.LastCachedInputTokens, data.LastCacheWriteInputTokens, data.LastOutputTokens, data.LastReasoningOutputTokens, data.LastTotalTokens, data.TotalInputTokens, data.TotalCachedInputTokens, data.TotalCacheWriteInputTokens, data.TotalOutputTokens, data.TotalReasoningOutputTokens, data.TotalTokens, data.ModelContextWindow).Returning("id").BuildWithFlavor(m.flavor)
	} else {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(conversationTokenUsageEventRowsExpectAutoSet).
			Values(data.ConversationId, data.UserUuid, data.TurnId, data.LastInputTokens, data.LastCachedInputTokens, data.LastCacheWriteInputTokens, data.LastOutputTokens, data.LastReasoningOutputTokens, data.LastTotalTokens, data.TotalInputTokens, data.TotalCachedInputTokens, data.TotalCacheWriteInputTokens, data.TotalOutputTokens, data.TotalReasoningOutputTokens, data.TotalTokens, data.ModelContextWindow).BuildWithFlavor(m.flavor)
	}
	var primaryKey int64
	var err error
	if session != nil {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = session.QueryRowCtx(ctx, &primaryKey, statement, args...)
			if err != nil {
				return err
			}
		} else {
			result, err := session.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	} else {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = m.conn.QueryRowCtx(ctx, &primaryKey, statement, args...)
		} else {
			result, err := m.conn.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	}
	data.Id = primaryKey
	return err
}

func (m *defaultConversationTokenUsageEventModel) Update(ctx context.Context, session sqlx.Session, data *ConversationTokenUsageEvent) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "conversation_id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "conversation_id"), data.ConversationId))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "user_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "user_uuid"), data.UserUuid))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "turn_id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "turn_id"), data.TurnId))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "last_input_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "last_input_tokens"), data.LastInputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "last_cached_input_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "last_cached_input_tokens"), data.LastCachedInputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "last_cache_write_input_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "last_cache_write_input_tokens"), data.LastCacheWriteInputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "last_output_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "last_output_tokens"), data.LastOutputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "last_reasoning_output_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "last_reasoning_output_tokens"), data.LastReasoningOutputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "last_total_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "last_total_tokens"), data.LastTotalTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "total_input_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "total_input_tokens"), data.TotalInputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "total_cached_input_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "total_cached_input_tokens"), data.TotalCachedInputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "total_cache_write_input_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "total_cache_write_input_tokens"), data.TotalCacheWriteInputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "total_output_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "total_output_tokens"), data.TotalOutputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "total_reasoning_output_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "total_reasoning_output_tokens"), data.TotalReasoningOutputTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "total_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "total_tokens"), data.TotalTokens))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "model_context_window")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "model_context_window"), data.ModelContextWindow))
	}
	if slices.Contains(conversationTokenUsageEventRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationTokenUsageEventModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customConversationTokenUsageEventModel) WithTable(f func(table string) string) conversationTokenUsageEventModel {
	mc := &customConversationTokenUsageEventModel{
		defaultConversationTokenUsageEventModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customConversationTokenUsageEventModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*ConversationTokenUsageEvent) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(conversationTokenUsageEventRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.ConversationId, data.UserUuid, data.TurnId, data.LastInputTokens, data.LastCachedInputTokens, data.LastCacheWriteInputTokens, data.LastOutputTokens, data.LastReasoningOutputTokens, data.LastTotalTokens, data.TotalInputTokens, data.TotalCachedInputTokens, data.TotalCacheWriteInputTokens, data.TotalOutputTokens, data.TotalReasoningOutputTokens, data.TotalTokens, data.ModelContextWindow)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customConversationTokenUsageEventModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(conversationTokenUsageEventFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*ConversationTokenUsageEvent
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customConversationTokenUsageEventModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customConversationTokenUsageEventModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, conversationTokenUsageEventFieldNames, conditions...)
}

func (m *customConversationTokenUsageEventModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customConversationTokenUsageEventModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ConversationTokenUsageEvent, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(conversationTokenUsageEventFieldNames), conditions...)
}

func (m *customConversationTokenUsageEventModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ConversationTokenUsageEvent, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(conversationTokenUsageEventFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp ConversationTokenUsageEvent
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customConversationTokenUsageEventModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationTokenUsageEvent, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(conversationTokenUsageEventFieldNames...)...).From(m.table), conditions...)

	var resp []*ConversationTokenUsageEvent
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customConversationTokenUsageEventModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customConversationTokenUsageEventModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
