// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package agent_token_quota

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	agentTokenQuotaFieldNames               []string
	agentTokenQuotaRows                     string
	agentTokenQuotaRowsExpectAutoFieldNames []string
	agentTokenQuotaRowsExpectAutoSet        string
)

const (
	Id                  condition.Field = "id"
	Scope               condition.Field = "scope"
	UserUuid            condition.Field = "user_uuid"
	Enabled             condition.Field = "enabled"
	FiveHourDisabled    condition.Field = "five_hour_disabled"
	FiveHourLimitTokens condition.Field = "five_hour_limit_tokens"
	SevenDayLimitTokens condition.Field = "seven_day_limit_tokens"
	QuotaResetAt        condition.Field = "quota_reset_at"
	CreateTime          condition.Field = "create_time"
	UpdateTime          condition.Field = "update_time"
)

func initAgentTokenQuotaVars(flavor sqlbuilder.Flavor) {
	agentTokenQuotaFieldNames = condition.RawFieldNamesWithFlavor(flavor, &AgentTokenQuota{})
	agentTokenQuotaRows = strings.Join(agentTokenQuotaFieldNames, ",")
	agentTokenQuotaRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, agentTokenQuotaFieldNames, "id", "create_time", "update_time")
	agentTokenQuotaRowsExpectAutoSet = strings.Join(agentTokenQuotaRowsExpectAutoFieldNames, ",")
}

type (
	agentTokenQuotaModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *AgentTokenQuota) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *AgentTokenQuota) error
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*AgentTokenQuota, error)
		FindOneByScope(ctx context.Context, session sqlx.Session, scope string) (*AgentTokenQuota, error)
		FindOneByUserUuid(ctx context.Context, session sqlx.Session, userUuid sql.NullString) (*AgentTokenQuota, error)
		Update(ctx context.Context, session sqlx.Session, data *AgentTokenQuota) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) agentTokenQuotaModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*AgentTokenQuota) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentTokenQuota, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*AgentTokenQuota, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*AgentTokenQuota, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*AgentTokenQuota, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*AgentTokenQuota, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentTokenQuota, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultAgentTokenQuotaModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	AgentTokenQuota struct {
		Id                  int64          `db:"id"`
		Scope               string         `db:"scope"`
		UserUuid            sql.NullString `db:"user_uuid"`
		Enabled             bool           `db:"enabled"`
		FiveHourDisabled    bool           `db:"five_hour_disabled"`
		FiveHourLimitTokens sql.NullInt64  `db:"five_hour_limit_tokens"`
		SevenDayLimitTokens sql.NullInt64  `db:"seven_day_limit_tokens"`
		QuotaResetAt        sql.NullTime   `db:"quota_reset_at"`
		CreateTime          time.Time      `db:"create_time"`
		UpdateTime          time.Time      `db:"update_time"`
	}
)

func newAgentTokenQuotaModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultAgentTokenQuotaModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initAgentTokenQuotaVars(o.Flavor)

	return &defaultAgentTokenQuotaModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "agent_token_quota"),
	}
}

// NewOriginalAgentTokenQuotaModel returns a original model for the database table.
func NewOriginalAgentTokenQuotaModel(conn sqlx.SqlConn) AgentTokenQuotaModel {
	return &customAgentTokenQuotaModel{
		defaultAgentTokenQuotaModel: newAgentTokenQuotaModel(conn),
	}
}

func (m *defaultAgentTokenQuotaModel) clone() *defaultAgentTokenQuotaModel {
	return &defaultAgentTokenQuotaModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultAgentTokenQuotaModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "id"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentTokenQuotaModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*AgentTokenQuota, error) {
	sb := sqlbuilder.Select(agentTokenQuotaRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "id"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp AgentTokenQuota
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentTokenQuotaModel) FindOneByScope(ctx context.Context, session sqlx.Session, scope string) (*AgentTokenQuota, error) {
	var resp AgentTokenQuota
	var err error

	sb := sqlbuilder.Select(agentTokenQuotaRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "scope = $1", scope)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentTokenQuotaModel) FindOneByUserUuid(ctx context.Context, session sqlx.Session, userUuid sql.NullString) (*AgentTokenQuota, error) {
	var resp AgentTokenQuota
	var err error

	sb := sqlbuilder.Select(agentTokenQuotaRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "user_uuid = $1", userUuid)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentTokenQuotaModel) Insert(ctx context.Context, session sqlx.Session, data *AgentTokenQuota) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(agentTokenQuotaRowsExpectAutoSet).
		Values(data.Scope, data.UserUuid, data.Enabled, data.FiveHourDisabled, data.FiveHourLimitTokens, data.SevenDayLimitTokens, data.QuotaResetAt).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultAgentTokenQuotaModel) InsertV2(ctx context.Context, session sqlx.Session, data *AgentTokenQuota) error {
	var statement string
	var args []any
	if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(agentTokenQuotaRowsExpectAutoSet).
			Values(data.Scope, data.UserUuid, data.Enabled, data.FiveHourDisabled, data.FiveHourLimitTokens, data.SevenDayLimitTokens, data.QuotaResetAt).Returning("id").BuildWithFlavor(m.flavor)
	} else {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(agentTokenQuotaRowsExpectAutoSet).
			Values(data.Scope, data.UserUuid, data.Enabled, data.FiveHourDisabled, data.FiveHourLimitTokens, data.SevenDayLimitTokens, data.QuotaResetAt).BuildWithFlavor(m.flavor)
	}
	var primaryKey int64
	var err error
	if session != nil {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = session.QueryRowCtx(ctx, &primaryKey, statement, args...)
			if err != nil {
				return err
			}
		} else {
			result, err := session.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	} else {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = m.conn.QueryRowCtx(ctx, &primaryKey, statement, args...)
		} else {
			result, err := m.conn.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	}
	data.Id = primaryKey
	return err
}

func (m *defaultAgentTokenQuotaModel) Update(ctx context.Context, session sqlx.Session, data *AgentTokenQuota) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "scope")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "scope"), data.Scope))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "user_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "user_uuid"), data.UserUuid))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "enabled")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "enabled"), data.Enabled))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "five_hour_disabled")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "five_hour_disabled"), data.FiveHourDisabled))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "five_hour_limit_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "five_hour_limit_tokens"), data.FiveHourLimitTokens))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "seven_day_limit_tokens")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "seven_day_limit_tokens"), data.SevenDayLimitTokens))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "quota_reset_at")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "quota_reset_at"), data.QuotaResetAt))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}
	if slices.Contains(agentTokenQuotaRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "update_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "update_time"), data.UpdateTime))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultAgentTokenQuotaModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customAgentTokenQuotaModel) WithTable(f func(table string) string) agentTokenQuotaModel {
	mc := &customAgentTokenQuotaModel{
		defaultAgentTokenQuotaModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customAgentTokenQuotaModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*AgentTokenQuota) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(agentTokenQuotaRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Scope, data.UserUuid, data.Enabled, data.FiveHourDisabled, data.FiveHourLimitTokens, data.SevenDayLimitTokens, data.QuotaResetAt)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customAgentTokenQuotaModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*AgentTokenQuota, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(agentTokenQuotaFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*AgentTokenQuota
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customAgentTokenQuotaModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*AgentTokenQuota, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customAgentTokenQuotaModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentTokenQuota, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, agentTokenQuotaFieldNames, conditions...)
}

func (m *customAgentTokenQuotaModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customAgentTokenQuotaModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*AgentTokenQuota, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(agentTokenQuotaFieldNames), conditions...)
}

func (m *customAgentTokenQuotaModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*AgentTokenQuota, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(agentTokenQuotaFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp AgentTokenQuota
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customAgentTokenQuotaModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*AgentTokenQuota, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(agentTokenQuotaFieldNames...)...).From(m.table), conditions...)

	var resp []*AgentTokenQuota
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customAgentTokenQuotaModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customAgentTokenQuotaModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
