// Code generated by jzero. DO NOT EDIT.
package v1conversation

import (
	"time"
)

var (
	_ = time.Now()
)

type Conversation struct {
	Id         string  `json:"id"`
	Title      string  `json:"title"`
	Status     string  `json:"status"`
	PinnedAt   *string `json:"pinnedAt,omitempty"`
	ArchivedAt *string `json:"archivedAt,omitempty"`
	GroupId    *string `json:"groupId,omitempty"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type CreateRequest struct {
	Title string `json:"title,optional"`
}

type DetailResponse struct {
	Conversation Conversation `json:"conversation"`
	SessionId    string       `json:"sessionId,omitempty"`
	Messages     []Message    `json:"messages"`
}

type EventsRequest struct {
	ConversationId  string `path:"conversation_id" validate:"required"`
	LastEventId     string `header:"Last-Event-ID,optional"`
	LastEventIdForm string `form:"lastEventId,optional"`
}

type EventsResponse struct {
	Id        int64  `json:"id"`
	Event     string `json:"event"`
	Data      string `json:"data"`
	CreatedAt string `json:"createdAt"`
}

type ListResponse struct {
	Conversations []Conversation `json:"conversations"`
}

type Message struct {
	Id        string `json:"id"`
	RunId     string `json:"runId"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type PathRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
}

type Run struct {
	Id          string                   `json:"id"`
	Sequence    int                      `json:"sequence"`
	Prompt      string                   `json:"prompt"`
	Status      string                   `json:"status"`
	Output      string                   `json:"output,omitempty"`
	Error       string                   `json:"error,omitempty"`
	ExitCode    int                      `json:"exitCode,omitempty"`
	Events      []map[string]interface{} `json:"events,omitempty"`
	CreatedAt   string                   `json:"createdAt"`
	StartedAt   *string                  `json:"startedAt,omitempty"`
	CompletedAt *string                  `json:"completedAt,omitempty"`
}

type SendMessageRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
	Content        string `json:"content" validate:"required"`
}

type SendMessageResponse struct {
	ConversationId string `json:"conversationId"`
	SessionId      string `json:"sessionId"`
	Run            Run    `json:"run"`
}

type UpdateRequest struct {
	ConversationId string  `path:"conversation_id" validate:"required"`
	Title          *string `json:"title,optional"`
	Pinned         *bool   `json:"pinned,optional"`
	Archived       *bool   `json:"archived,optional"`
	GroupId        *string `json:"groupId,optional"`
}
