// Code generated by jzero. DO NOT EDIT.
package v1conversation

import (
	"time"
)

var (
	_ = time.Now()
)

type CancelTurnResponse struct {
}

type Conversation struct {
	Id               string  `json:"id"`
	Title            string  `json:"title"`
	Status           string  `json:"status"`
	PinnedAt         *string `json:"pinnedAt,omitempty"`
	ArchivedAt       *string `json:"archivedAt,omitempty"`
	GroupId          *string `json:"groupId,omitempty"`
	Running          bool    `json:"running"`
	RunningStartedAt *string `json:"runningStartedAt,omitempty"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
}

type CreateRequest struct {
	GroupId *string `json:"groupId,optional"`
}

type DeleteResponse struct {
}

type DetailResponse struct {
	Conversation Conversation `json:"conversation"`
	EventCursor  int64        `json:"eventCursor"`
	Turns        []Turn       `json:"turns"`
}

type EventsRequest struct {
	ConversationId  string `path:"conversation_id" validate:"required"`
	LastEventId     string `header:"Last-Event-ID,optional"`
	LastEventIdForm string `form:"lastEventId,optional"`
}

type EventsResponse struct {
	Id        int64  `json:"id"`
	Event     string `json:"event"`
	Data      string `json:"data"`
	CreatedAt string `json:"createdAt"`
}

type GeneratedImage struct {
	Id      string `json:"id"`
	DataUrl string `json:"dataUrl"`
	Alt     string `json:"alt"`
}

type ListResponse struct {
	Conversations []Conversation `json:"conversations"`
}

type MetadataResponse struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	UpdatedAt string `json:"updatedAt"`
}

type PathRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
}

type SendMessageRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
	Content        string `json:"content" validate:"required"`
}

type StartedTurn struct {
	Id        string `json:"id"`
	StartedAt string `json:"startedAt"`
}

type StatsResponse struct {
	TotalConversations    int64 `json:"totalConversations"`
	ActiveConversations   int64 `json:"activeConversations"`
	RunningConversations  int64 `json:"runningConversations"`
	ArchivedConversations int64 `json:"archivedConversations"`
	TotalTokens           int64 `json:"totalTokens"`
	TokenUsageAvailable   bool  `json:"tokenUsageAvailable"`
}

type Turn struct {
	Id          string                   `json:"id"`
	Status      string                   `json:"status"`
	StartedAt   *string                  `json:"startedAt,omitempty"`
	CompletedAt *string                  `json:"completedAt,omitempty"`
	DurationMs  *int64                   `json:"durationMs,omitempty"`
	Error       string                   `json:"error,omitempty"`
	Items       []map[string]interface{} `json:"items"`
}

type UpdateRequest struct {
	ConversationId string  `path:"conversation_id" validate:"required"`
	Title          *string `json:"title,optional"`
	Pinned         *bool   `json:"pinned,optional"`
	Archived       *bool   `json:"archived,optional"`
	GroupId        *string `json:"groupId,optional"`
}

type WorkspaceEntry struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type"`
	Size int64  `json:"size"`
}

type WorkspaceFilesResponse struct {
	Entries []WorkspaceEntry `json:"entries"`
}
