// Code generated by jzero. DO NOT EDIT.
package v1conversation

import (
	"time"
)

var (
	_ = time.Now()
)

type CancelTurnResponse struct {
}

type Conversation struct {
	Id               string  `json:"id"`
	Title            string  `json:"title"`
	Status           string  `json:"status"`
	PinnedAt         *string `json:"pinnedAt,omitempty"`
	ArchivedAt       *string `json:"archivedAt,omitempty"`
	GroupId          *string `json:"groupId,omitempty"`
	Running          bool    `json:"running"`
	RunningStartedAt *string `json:"runningStartedAt,omitempty"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
}

type ConversationTrendPoint struct {
	Period                string `json:"period"`
	TotalConversations    int64  `json:"totalConversations"`
	ArchivedConversations int64  `json:"archivedConversations"`
}

type ConversationTrendRequest struct {
	Dimension string `form:"dimension,default=day,optional" validate:"oneof=day month"`
}

type ConversationTrendResponse struct {
	Dimension string                   `json:"dimension"`
	Points    []ConversationTrendPoint `json:"points"`
}

type CreateRequest struct {
	GroupId *string `json:"groupId,optional"`
}

type DeleteResponse struct {
}

type DetailResponse struct {
	Conversation   Conversation `json:"conversation"`
	StreamPosition string       `json:"streamPosition"`
	Turns          []Turn       `json:"turns"`
}

type EventsRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
}

type EventsResponse struct {
	Event string `json:"event"`
	Data  string `json:"data"`
}

type GeneratedImage struct {
	Id      string `json:"id"`
	DataUrl string `json:"dataUrl"`
	Alt     string `json:"alt"`
}

type ListResponse struct {
	Conversations []Conversation `json:"conversations"`
}

type MetadataResponse struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	UpdatedAt string `json:"updatedAt"`
}

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}

type PageResponse struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}

type PathRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
}

type SendMessageRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
	Content        string `json:"content" validate:"required"`
}

type StartedTurn struct {
	Id        string `json:"id"`
	StartedAt string `json:"startedAt"`
}

type StatsResponse struct {
	TotalConversations    int64 `json:"totalConversations"`
	ActiveConversations   int64 `json:"activeConversations"`
	RunningConversations  int64 `json:"runningConversations"`
	ArchivedConversations int64 `json:"archivedConversations"`
	TotalTokens           int64 `json:"totalTokens"`
	TokenUsageAvailable   bool  `json:"tokenUsageAvailable"`
}

type TokenQuotaStatusResponse struct {
	Enabled      bool             `json:"enabled"`
	FiveHour     TokenQuotaWindow `json:"fiveHour"`
	SevenDay     TokenQuotaWindow `json:"sevenDay"`
	QuotaResetAt *string          `json:"quotaResetAt,omitempty"`
}

type TokenQuotaWindow struct {
	Limited          bool    `json:"limited"`
	UsedTokens       int64   `json:"usedTokens"`
	LimitTokens      int64   `json:"limitTokens"`
	RemainingTokens  int64   `json:"remainingTokens"`
	RemainingPercent float64 `json:"remainingPercent"`
	Source           string  `json:"source"`
	ResetAt          *string `json:"resetAt,omitempty"`
}

type TokenUsageAccount struct {
	UserUuid          string `json:"userUuid"`
	Username          string `json:"username"`
	Nickname          string `json:"nickname"`
	TotalTokens       int64  `json:"totalTokens"`
	ConversationCount int64  `json:"conversationCount"`
	TurnCount         int64  `json:"turnCount"`
}

type TokenUsageConversation struct {
	ConversationId string           `json:"conversationId"`
	TotalTokens    int64            `json:"totalTokens"`
	TurnCount      int64            `json:"turnCount"`
	FirstUsedAt    string           `json:"firstUsedAt"`
	LastUsedAt     string           `json:"lastUsedAt"`
	Turns          []TokenUsageTurn `json:"turns"`
}

type TokenUsageConversationsRequest struct {
	PageRequest
	UserUuid       string `form:"userUuid" validate:"required"`
	ConversationId string `form:"conversationId,optional"`
}

type TokenUsageConversationsResponse struct {
	PageResponse
	Conversations []TokenUsageConversation `json:"conversations"`
}

type TokenUsageDetailsRequest struct {
	PageRequest
	Username string `form:"username,optional"`
}

type TokenUsageDetailsResponse struct {
	PageResponse
	Summary  TokenUsageSummary   `json:"summary"`
	Accounts []TokenUsageAccount `json:"accounts"`
}

type TokenUsageSummary struct {
	InputTokens           int64 `json:"inputTokens"`
	CachedInputTokens     int64 `json:"cachedInputTokens"`
	CacheWriteInputTokens int64 `json:"cacheWriteInputTokens"`
	OutputTokens          int64 `json:"outputTokens"`
	ReasoningOutputTokens int64 `json:"reasoningOutputTokens"`
	TotalTokens           int64 `json:"totalTokens"`
}

type TokenUsageTrendPoint struct {
	Period string `json:"period"`
	Tokens int64  `json:"tokens"`
}

type TokenUsageTrendRequest struct {
	Dimension string `form:"dimension,default=day,optional" validate:"oneof=day month"`
}

type TokenUsageTrendResponse struct {
	Dimension string                 `json:"dimension"`
	Points    []TokenUsageTrendPoint `json:"points"`
}

type TokenUsageTurn struct {
	TurnId                string `json:"turnId"`
	InputTokens           int64  `json:"inputTokens"`
	CachedInputTokens     int64  `json:"cachedInputTokens"`
	CacheWriteInputTokens int64  `json:"cacheWriteInputTokens"`
	OutputTokens          int64  `json:"outputTokens"`
	ReasoningOutputTokens int64  `json:"reasoningOutputTokens"`
	TotalTokens           int64  `json:"totalTokens"`
	ModelContextWindow    *int64 `json:"modelContextWindow,omitempty"`
	StartedAt             string `json:"startedAt"`
	UpdatedAt             string `json:"updatedAt"`
}

type Turn struct {
	Id          string                   `json:"id"`
	Status      string                   `json:"status"`
	StartedAt   *string                  `json:"startedAt,omitempty"`
	CompletedAt *string                  `json:"completedAt,omitempty"`
	DurationMs  *int64                   `json:"durationMs,omitempty"`
	Error       string                   `json:"error,omitempty"`
	Items       []map[string]interface{} `json:"items"`
}

type UpdateRequest struct {
	ConversationId string  `path:"conversation_id" validate:"required"`
	Title          *string `json:"title,optional"`
	Pinned         *bool   `json:"pinned,optional"`
	Archived       *bool   `json:"archived,optional"`
	GroupId        *string `json:"groupId,optional"`
}

type WorkspaceEntry struct {
	Name     string           `json:"name"`
	Path     string           `json:"path"`
	Type     string           `json:"type"`
	Children []WorkspaceEntry `json:"children"`
}

type WorkspaceFileRequest struct {
	ConversationId string `path:"conversation_id" validate:"required"`
	FilePath       string `form:"path" validate:"required"`
}

type WorkspaceFileResponse struct {
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
	DataBase64  string `json:"dataBase64"`
}

type WorkspaceFilesResponse struct {
	Files []WorkspaceEntry `json:"files"`
}
