// Code generated by jzero. DO NOT EDIT.
package v1agentcharacter

import (
	"time"
)

var (
	_ = time.Now()
)

type Character struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Prompt      string `json:"prompt"`
	Builtin     bool   `json:"builtin"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type CreateRequest struct {
	Name        string `json:"name" validate:"required,max=80"`
	Description string `json:"description,optional" validate:"max=240"`
	Prompt      string `json:"prompt" validate:"required,max=16000"`
}

type DeleteResponse struct {
}

type ListResponse struct {
	Characters []Character `json:"characters"`
}

type PathRequest struct {
	CharacterId string `path:"character_id" validate:"required"`
}

type UpdateRequest struct {
	CharacterId string  `path:"character_id" validate:"required"`
	Name        *string `json:"name,optional" validate:"omitempty,max=80"`
	Description *string `json:"description,optional" validate:"omitempty,max=240"`
	Prompt      *string `json:"prompt,optional" validate:"omitempty,max=16000"`
}
