// Code generated by jzero. DO NOT EDIT.
package v1conversationgroup

import (
	"time"
)

var (
	_ = time.Now()
)

type ConversationGroup struct {
	Id        string  `json:"id"`
	Name      string  `json:"name"`
	PinnedAt  *string `json:"pinnedAt,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type CreateRequest struct {
	Name   string `json:"name" validate:"required,max=40"`
	Pinned *bool  `json:"pinned,optional"`
}

type DeleteResponse struct {
}

type ArchiveConversationsResponse struct {
}

type DeleteArchivedConversationsResponse struct {
}

type ListResponse struct {
	Groups []ConversationGroup `json:"groups"`
}

type PathRequest struct {
	GroupId string `path:"group_id" validate:"required"`
}

type UpdateRequest struct {
	GroupId string  `path:"group_id" validate:"required"`
	Name    *string `json:"name,optional" validate:"omitempty,max=40"`
	Pinned  *bool   `json:"pinned,optional"`
}
