// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package conversation_group

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	conversationGroupFieldNames               []string
	conversationGroupRows                     string
	conversationGroupRowsExpectAutoFieldNames []string
	conversationGroupRowsExpectAutoSet        string
)

const (
	Uuid       condition.Field = "uuid"
	UserUuid   condition.Field = "user_uuid"
	Name       condition.Field = "name"
	CreateTime condition.Field = "create_time"
	UpdateTime condition.Field = "update_time"
)

func initConversationGroupVars(flavor sqlbuilder.Flavor) {
	conversationGroupFieldNames = condition.RawFieldNamesWithFlavor(flavor, &ConversationGroup{})
	conversationGroupRows = strings.Join(conversationGroupFieldNames, ",")
	conversationGroupRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, conversationGroupFieldNames, "`create_time`", "`update_time`")
	conversationGroupRowsExpectAutoSet = strings.Join(conversationGroupRowsExpectAutoFieldNames, ",")
}

type (
	conversationGroupModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *ConversationGroup) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *ConversationGroup) error
		FindOne(ctx context.Context, session sqlx.Session, uuid string) (*ConversationGroup, error)
		Update(ctx context.Context, session sqlx.Session, data *ConversationGroup) error
		Delete(ctx context.Context, session sqlx.Session, uuid string) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) conversationGroupModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*ConversationGroup) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationGroup, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ConversationGroup, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ConversationGroup, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ConversationGroup, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ConversationGroup, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationGroup, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultConversationGroupModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	ConversationGroup struct {
		Uuid       string    `db:"uuid"`
		UserUuid   string    `db:"user_uuid"`
		Name       string    `db:"name"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newConversationGroupModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultConversationGroupModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initConversationGroupVars(o.Flavor)

	return &defaultConversationGroupModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "conversation_group"),
	}
}

// NewOriginalConversationGroupModel returns a original model for the database table.
func NewOriginalConversationGroupModel(conn sqlx.SqlConn) ConversationGroupModel {
	return &customConversationGroupModel{
		defaultConversationGroupModel: newConversationGroupModel(conn),
	}
}

func (m *defaultConversationGroupModel) clone() *defaultConversationGroupModel {
	return &defaultConversationGroupModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultConversationGroupModel) Delete(ctx context.Context, session sqlx.Session, uuid string) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`uuid`"), uuid))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationGroupModel) FindOne(ctx context.Context, session sqlx.Session, uuid string) (*ConversationGroup, error) {
	sb := sqlbuilder.Select(conversationGroupRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`uuid`"), uuid))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp ConversationGroup
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationGroupModel) Insert(ctx context.Context, session sqlx.Session, data *ConversationGroup) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(conversationGroupRowsExpectAutoSet).
		Values(data.Uuid, data.UserUuid, data.Name).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultConversationGroupModel) InsertV2(ctx context.Context, session sqlx.Session, data *ConversationGroup) error {
	var statement string
	var args []any
	statement, args = sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(conversationGroupRowsExpectAutoSet).
		Values(data.Uuid, data.UserUuid, data.Name).BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationGroupModel) Update(ctx context.Context, session sqlx.Session, data *ConversationGroup) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(conversationGroupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	}
	if slices.Contains(conversationGroupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "user_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "user_uuid"), data.UserUuid))
	}
	if slices.Contains(conversationGroupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "name")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "name"), data.Name))
	}
	if slices.Contains(conversationGroupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}
	if slices.Contains(conversationGroupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "update_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "update_time"), data.UpdateTime))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`uuid`"), data.Uuid))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultConversationGroupModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customConversationGroupModel) WithTable(f func(table string) string) conversationGroupModel {
	mc := &customConversationGroupModel{
		defaultConversationGroupModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customConversationGroupModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*ConversationGroup) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(conversationGroupRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Uuid, data.UserUuid, data.Name)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customConversationGroupModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ConversationGroup, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(conversationGroupFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*ConversationGroup
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customConversationGroupModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ConversationGroup, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customConversationGroupModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationGroup, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, conversationGroupFieldNames, conditions...)
}

func (m *customConversationGroupModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customConversationGroupModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ConversationGroup, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(conversationGroupFieldNames), conditions...)
}

func (m *customConversationGroupModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ConversationGroup, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(conversationGroupFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp ConversationGroup
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customConversationGroupModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ConversationGroup, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(conversationGroupFieldNames...)...).From(m.table), conditions...)

	var resp []*ConversationGroup
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customConversationGroupModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customConversationGroupModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
