// Code generated by jzero. DO NOT EDIT.
package v1agenttoken

import (
	"time"
)

var (
	_ = time.Now()
)

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}

type PageResponse struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}

type TokenQuotaStatusResponse struct {
	Enabled      bool             `json:"enabled"`
	FiveHour     TokenQuotaWindow `json:"fiveHour"`
	SevenDay     TokenQuotaWindow `json:"sevenDay"`
	QuotaResetAt *string          `json:"quotaResetAt,omitempty"`
}

type TokenQuotaWindow struct {
	Limited          bool    `json:"limited"`
	UsedTokens       int64   `json:"usedTokens"`
	LimitTokens      int64   `json:"limitTokens"`
	RemainingTokens  int64   `json:"remainingTokens"`
	RemainingPercent float64 `json:"remainingPercent"`
	Source           string  `json:"source"`
	ResetAt          *string `json:"resetAt,omitempty"`
}

type TokenUsageAccount struct {
	UserUuid          string `json:"userUuid"`
	Username          string `json:"username"`
	Nickname          string `json:"nickname"`
	TotalTokens       int64  `json:"totalTokens"`
	ConversationCount int64  `json:"conversationCount"`
	TurnCount         int64  `json:"turnCount"`
}

type TokenUsageConversation struct {
	ConversationId string           `json:"conversationId"`
	TotalTokens    int64            `json:"totalTokens"`
	TurnCount      int64            `json:"turnCount"`
	FirstUsedAt    string           `json:"firstUsedAt"`
	LastUsedAt     string           `json:"lastUsedAt"`
	Turns          []TokenUsageTurn `json:"turns"`
}

type TokenUsageConversationsRequest struct {
	PageRequest
	UserUuid       string `form:"userUuid" validate:"required"`
	ConversationId string `form:"conversationId,optional"`
}

type TokenUsageConversationsResponse struct {
	PageResponse
	Conversations []TokenUsageConversation `json:"conversations"`
}

type TokenUsageDetailsRequest struct {
	PageRequest
	Username string `form:"username,optional"`
}

type TokenUsageDetailsResponse struct {
	PageResponse
	Summary  TokenUsageSummary   `json:"summary"`
	Accounts []TokenUsageAccount `json:"accounts"`
}

type TokenUsageSummary struct {
	InputTokens           int64 `json:"inputTokens"`
	CachedInputTokens     int64 `json:"cachedInputTokens"`
	CacheWriteInputTokens int64 `json:"cacheWriteInputTokens"`
	OutputTokens          int64 `json:"outputTokens"`
	ReasoningOutputTokens int64 `json:"reasoningOutputTokens"`
	TotalTokens           int64 `json:"totalTokens"`
}

type TokenUsageTrendPoint struct {
	Period string `json:"period"`
	Tokens int64  `json:"tokens"`
}

type TokenUsageTrendRequest struct {
	Dimension string `form:"dimension,default=day,optional" validate:"oneof=day month"`
}

type TokenUsageTrendResponse struct {
	Dimension string                 `json:"dimension"`
	Points    []TokenUsageTrendPoint `json:"points"`
}

type TokenUsageTurn struct {
	TurnId                string `json:"turnId"`
	InputTokens           int64  `json:"inputTokens"`
	CachedInputTokens     int64  `json:"cachedInputTokens"`
	CacheWriteInputTokens int64  `json:"cacheWriteInputTokens"`
	OutputTokens          int64  `json:"outputTokens"`
	ReasoningOutputTokens int64  `json:"reasoningOutputTokens"`
	TotalTokens           int64  `json:"totalTokens"`
	ModelContextWindow    *int64 `json:"modelContextWindow,omitempty"`
	StartedAt             string `json:"startedAt"`
	UpdatedAt             string `json:"updatedAt"`
}
