// Code generated by jzero. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"github.com/zeromicro/go-zero/rest"

	swagger "github.com/jzero-io/agentrazor/server/internal/handler/swagger"
	v1auth "github.com/jzero-io/agentrazor/server/internal/handler/v1/auth"
	v1conversation "github.com/jzero-io/agentrazor/server/internal/handler/v1/conversation"
	v1conversationgroup "github.com/jzero-io/agentrazor/server/internal/handler/v1/conversation/group"
	v1manageagent "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/agent"
	v1manageemail "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/email"
	v1managemenu "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/menu"
	v1managerole "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/role"
	v1manageuser "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/user"
	v1route "github.com/jzero-io/agentrazor/server/internal/handler/v1/route"
	version "github.com/jzero-io/agentrazor/server/internal/handler/version"
	"github.com/jzero-io/agentrazor/server/internal/svc"
)

var (
	_ = http.StatusOK
	_ = time.Now()
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/swagger",
					Handler: swagger.Swagger(serverCtx),
				},
			},
		)
	}
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/code-login",
					Handler: v1auth.CodeLogin(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/pwd-login",
					Handler: v1auth.PwdLogin(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/refreshToken",
					Handler: v1auth.RefreshToken(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/register",
					Handler: v1auth.Register(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/resetPassword",
					Handler: v1auth.ResetPassword(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/auth/sendVerificationCode",
					Handler: v1auth.SendVerificationCode(serverCtx),
				},
			},
			rest.WithPrefix("/api/v1"),
		)

		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/getUserInfo",
					Handler: v1auth.GetUserInfo(serverCtx),
				},
			},
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{

						Method:  http.MethodGet,
						Path:    "/conversations",
						Handler: v1conversation.List(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/conversations/stats",
						Handler: v1conversation.Stats(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/conversations",
						Handler: v1conversation.SendMessage(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/conversations/:conversation_id/metadata",
						Handler: v1conversation.Metadata(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/conversations/:conversation_id",
						Handler: v1conversation.Get(serverCtx),
					},
					{

						Method:  http.MethodPatch,
						Path:    "/conversations/:conversation_id",
						Handler: v1conversation.Update(serverCtx),
					},
					{

						Method:  http.MethodDelete,
						Path:    "/conversations/:conversation_id",
						Handler: v1conversation.Delete(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/conversations/:conversation_id/turn/cancel",
						Handler: v1conversation.CancelTurn(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)

		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{

						Method:  http.MethodGet,
						Path:    "/conversations/:conversation_id/events",
						Handler: v1conversation.StreamEvents(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
			rest.WithSSE(),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/conversation-groups",
						Handler: v1conversationgroup.List(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/conversation-groups",
						Handler: v1conversationgroup.Create(serverCtx),
					},
					{
						Method:  http.MethodPatch,
						Path:    "/conversation-groups/:group_id",
						Handler: v1conversationgroup.Update(serverCtx),
					},
					{
						Method:  http.MethodDelete,
						Path:    "/conversation-groups/:group_id",
						Handler: v1conversationgroup.Delete(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/conversation-groups/:group_id/archive-conversations",
						Handler: v1conversationgroup.ArchiveConversations(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/conversation-groups/:group_id/delete-archived-conversations",
						Handler: v1conversationgroup.DeleteArchivedConversations(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/config/file",
						Handler: v1manageagent.ConfigFile(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/config/file",
						Handler: v1manageagent.UpdateConfigFile(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/config/files",
						Handler: v1manageagent.ListConfigFiles(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/runtime/restart",
						Handler: v1manageagent.RestartRuntime(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/runtime/status",
						Handler: v1manageagent.RuntimeStatus(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/skills",
						Handler: v1manageagent.ListSkills(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/skills/:skill_name",
						Handler: v1manageagent.SkillDetail(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/skills/:skill_name/delete",
						Handler: v1manageagent.DeleteSkill(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/skills/:skill_name/file",
						Handler: v1manageagent.UpdateSkillFile(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/skills/upload",
						Handler: v1manageagent.UploadSkill(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/manage/email/config",
						Handler: v1manageemail.GetConfig(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/email/config",
						Handler: v1manageemail.SaveConfig(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/email/test",
						Handler: v1manageemail.TestConfig(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/manage/addMenu",
						Handler: v1managemenu.Add(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/deleteMenu",
						Handler: v1managemenu.Delete(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/editMenu",
						Handler: v1managemenu.Edit(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getAllPages",
						Handler: v1managemenu.GetAllPages(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getMenuList",
						Handler: v1managemenu.List(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getMenuTree",
						Handler: v1managemenu.Tree(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/manage/addRole",
						Handler: v1managerole.Add(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/deleteRole",
						Handler: v1managerole.Delete(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/editRole",
						Handler: v1managerole.Edit(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getAllRoles",
						Handler: v1managerole.GetAll(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getRoleHome",
						Handler: v1managerole.GetHome(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getRoleList",
						Handler: v1managerole.List(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getRoleMenus",
						Handler: v1managerole.GetMenus(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/setRoleMenus",
						Handler: v1managerole.SetMenus(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/updateRoleHome",
						Handler: v1managerole.UpdateHome(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/manage/addUser",
						Handler: v1manageuser.Add(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/deleteUser",
						Handler: v1manageuser.Delete(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/editUser",
						Handler: v1manageuser.Edit(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getUserList",
						Handler: v1manageuser.List(serverCtx),
					},
				}...,
			),
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/route/getUserRoutes",
					Handler: v1route.GetUserRoutes(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/route/isRouteExist",
					Handler: v1route.IsRouteExist(serverCtx),
				},
			},
			rest.WithJwt(serverCtx.MustGetConfig().Jwt.AccessSecret),
			rest.WithPrefix("/api/v1"),
		)

		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/route/getConstantRoutes",
					Handler: v1route.GetConstantRoutes(serverCtx),
				},
			},
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: version.Version(serverCtx),
				},
			},
			rest.WithPrefix("/api"),
		)
	}

}
