// Code generated by jzero. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"github.com/zeromicro/go-zero/rest"

	swagger "github.com/jzero-io/agentrazor/server/internal/handler/swagger"
	v1agentapikey "github.com/jzero-io/agentrazor/server/internal/handler/v1/agent/apikey"
	v1agentconversation "github.com/jzero-io/agentrazor/server/internal/handler/v1/agent/conversation"
	v1agentconversationgroup "github.com/jzero-io/agentrazor/server/internal/handler/v1/agent/conversation/group"
	v1agenttoken "github.com/jzero-io/agentrazor/server/internal/handler/v1/agent/token"
	v1auth "github.com/jzero-io/agentrazor/server/internal/handler/v1/auth"
	v1manageagent "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/agent"
	v1manageemail "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/email"
	v1managemenu "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/menu"
	v1managerole "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/role"
	v1manageuser "github.com/jzero-io/agentrazor/server/internal/handler/v1/manage/user"
	v1route "github.com/jzero-io/agentrazor/server/internal/handler/v1/route"
	version "github.com/jzero-io/agentrazor/server/internal/handler/version"
	"github.com/jzero-io/agentrazor/server/internal/svc"
)

var (
	_ = http.StatusOK
	_ = time.Now()
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/swagger",
					Handler: swagger.Swagger(serverCtx),
				},
			},
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{

						Method:  http.MethodGet,
						Path:    "/agent/api-keys",
						Handler: v1agentapikey.List(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/agent/api-keys",
						Handler: v1agentapikey.Create(serverCtx),
					},
					{

						Method:  http.MethodDelete,
						Path:    "/agent/api-keys/:id",
						Handler: v1agentapikey.Delete(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{

						Method:  http.MethodGet,
						Path:    "/agent/conversation",
						Handler: v1agentconversation.List(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/agent/conversation",
						Handler: v1agentconversation.Create(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/conversation/:conversation_id",
						Handler: v1agentconversation.Get(serverCtx),
					},
					{

						Method:  http.MethodPatch,
						Path:    "/agent/conversation/:conversation_id",
						Handler: v1agentconversation.Update(serverCtx),
					},
					{

						Method:  http.MethodDelete,
						Path:    "/agent/conversation/:conversation_id",
						Handler: v1agentconversation.Delete(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/agent/conversation/:conversation_id/attachments",
						Handler: v1agentconversation.UploadAttachment(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/agent/conversation/:conversation_id/messages",
						Handler: v1agentconversation.SendMessage(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/conversation/:conversation_id/metadata",
						Handler: v1agentconversation.Metadata(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/agent/conversation/:conversation_id/turn/cancel",
						Handler: v1agentconversation.CancelTurn(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/conversation/:conversation_id/workspace/file",
						Handler: v1agentconversation.WorkspaceFile(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/conversation/:conversation_id/workspace/files",
						Handler: v1agentconversation.WorkspaceFiles(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/conversation/stats",
						Handler: v1agentconversation.Stats(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)

		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{

						Method:  http.MethodGet,
						Path:    "/agent/conversation/:conversation_id/events",
						Handler: v1agentconversation.StreamEvents(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
			rest.WithSSE(),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/agent/conversation-groups",
						Handler: v1agentconversationgroup.List(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/agent/conversation-groups",
						Handler: v1agentconversationgroup.Create(serverCtx),
					},
					{
						Method:  http.MethodPatch,
						Path:    "/agent/conversation-groups/:group_id",
						Handler: v1agentconversationgroup.Update(serverCtx),
					},
					{
						Method:  http.MethodDelete,
						Path:    "/agent/conversation-groups/:group_id",
						Handler: v1agentconversationgroup.Delete(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/agent/conversation-groups/:group_id/archive-conversations",
						Handler: v1agentconversationgroup.ArchiveConversations(serverCtx),
					},
					{

						Method:  http.MethodPost,
						Path:    "/agent/conversation-groups/:group_id/delete-archived-conversations",
						Handler: v1agentconversationgroup.DeleteArchivedConversations(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Agent},
				[]rest.Route{
					{

						Method:  http.MethodGet,
						Path:    "/agent/token/quota",
						Handler: v1agenttoken.QuotaStatus(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/token/usage-conversations",
						Handler: v1agenttoken.UsageConversations(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/token/usage-details",
						Handler: v1agenttoken.UsageDetails(serverCtx),
					},
					{

						Method:  http.MethodGet,
						Path:    "/agent/token/usage-trend",
						Handler: v1agenttoken.UsageTrend(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/code-login",
					Handler: v1auth.CodeLogin(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/pwd-login",
					Handler: v1auth.PwdLogin(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/refreshToken",
					Handler: v1auth.RefreshToken(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/register",
					Handler: v1auth.Register(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/resetPassword",
					Handler: v1auth.ResetPassword(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/auth/sendVerificationCode",
					Handler: v1auth.SendVerificationCode(serverCtx),
				},
			},
			rest.WithPrefix("/api/v1"),
		)

		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/auth/getUserInfo",
						Handler: v1auth.GetUserInfo(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/auth/api-key",
						Handler: v1manageagent.LoginApiKey(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/auth/chatgpt/start",
						Handler: v1manageagent.StartChatGPTLogin(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/auth/logout",
						Handler: v1manageagent.Logout(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/auth/status",
						Handler: v1manageagent.GetAccountStatus(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/settings",
						Handler: v1manageagent.GetSettings(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/settings",
						Handler: v1manageagent.SaveSettings(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/skills",
						Handler: v1manageagent.ListSkills(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/skills/:skill_name",
						Handler: v1manageagent.SkillDetail(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/skills/:skill_name/delete",
						Handler: v1manageagent.DeleteSkill(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/skills/:skill_name/file",
						Handler: v1manageagent.UpdateSkillFile(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/skills/:skill_name/status",
						Handler: v1manageagent.SetSkillStatus(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/skills/upload",
						Handler: v1manageagent.UploadSkill(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/token-quota/global",
						Handler: v1manageagent.GetTokenQuotaGlobal(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/token-quota/global",
						Handler: v1manageagent.SaveTokenQuotaGlobal(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/agent/token-quota/users/:user_uuid",
						Handler: v1manageagent.GetUserTokenQuota(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/token-quota/users/:user_uuid",
						Handler: v1manageagent.SaveUserTokenQuota(serverCtx),
					},
					{
						Method:  http.MethodDelete,
						Path:    "/manage/agent/token-quota/users/:user_uuid",
						Handler: v1manageagent.DeleteUserTokenQuota(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/agent/token-quota/users/:user_uuid/reset",
						Handler: v1manageagent.ResetUserTokenQuota(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)

		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/home/overview",
						Handler: v1manageagent.HomeOverview(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/manage/email/config",
						Handler: v1manageemail.GetConfig(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/email/config",
						Handler: v1manageemail.SaveConfig(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/email/test",
						Handler: v1manageemail.TestConfig(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/manage/addMenu",
						Handler: v1managemenu.Add(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/deleteMenu",
						Handler: v1managemenu.Delete(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/editMenu",
						Handler: v1managemenu.Edit(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getAllPages",
						Handler: v1managemenu.GetAllPages(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getMenuList",
						Handler: v1managemenu.List(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getMenuTree",
						Handler: v1managemenu.Tree(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/manage/addRole",
						Handler: v1managerole.Add(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/deleteRole",
						Handler: v1managerole.Delete(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/editRole",
						Handler: v1managerole.Edit(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getAllRoles",
						Handler: v1managerole.GetAll(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getRoleHome",
						Handler: v1managerole.GetHome(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getRoleList",
						Handler: v1managerole.List(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getRoleMenus",
						Handler: v1managerole.GetMenus(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/setRoleMenus",
						Handler: v1managerole.SetMenus(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/updateRoleHome",
						Handler: v1managerole.UpdateHome(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/manage/addUser",
						Handler: v1manageuser.Add(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/deleteUser",
						Handler: v1manageuser.Delete(serverCtx),
					},
					{
						Method:  http.MethodPost,
						Path:    "/manage/editUser",
						Handler: v1manageuser.Edit(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/manage/getUserList",
						Handler: v1manageuser.List(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			rest.WithMiddlewares(
				[]rest.Middleware{serverCtx.Authx},
				[]rest.Route{
					{
						Method:  http.MethodGet,
						Path:    "/route/getUserRoutes",
						Handler: v1route.GetUserRoutes(serverCtx),
					},
					{
						Method:  http.MethodGet,
						Path:    "/route/isRouteExist",
						Handler: v1route.IsRouteExist(serverCtx),
					},
				}...,
			),
			rest.WithPrefix("/api/v1"),
		)

		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/route/getConstantRoutes",
					Handler: v1route.GetConstantRoutes(serverCtx),
				},
			},
			rest.WithPrefix("/api/v1"),
		)
	}
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: version.Version(serverCtx),
				},
			},
			rest.WithPrefix("/api"),
		)
	}

}
