// Code generated by jzero. DO NOT EDIT.

package handler

import (
	"net/http"
	"path"
	"strings"
	"sync"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/search"
)

var RoutesCodesMap = map[string]string{
	"GET:/swagger":                                                                   "swagger:swagger",
	"GET:/api/v1/agent/api-keys":                                                     "v1:agent:apikey:list",
	"POST:/api/v1/agent/api-keys":                                                    "v1:agent:apikey:create",
	"DELETE:/api/v1/agent/api-keys/:id":                                              "v1:agent:apikey:delete",
	"GET:/api/v1/agent/characters":                                                   "v1:agent:character:list",
	"POST:/api/v1/agent/characters":                                                  "v1:agent:character:create",
	"DELETE:/api/v1/agent/characters/:character_id":                                  "v1:agent:character:delete",
	"PATCH:/api/v1/agent/characters/:character_id":                                   "v1:agent:character:update",
	"GET:/api/v1/agent/conversation":                                                 "v1:agent:conversation:list",
	"POST:/api/v1/agent/conversation":                                                "v1:agent:conversation:create",
	"DELETE:/api/v1/agent/conversation/:conversation_id":                             "v1:agent:conversation:delete",
	"GET:/api/v1/agent/conversation/:conversation_id":                                "v1:agent:conversation:get",
	"PATCH:/api/v1/agent/conversation/:conversation_id":                              "v1:agent:conversation:update",
	"POST:/api/v1/agent/conversation/:conversation_id/attachments":                   "v1:agent:conversation:uploadAttachment",
	"GET:/api/v1/agent/conversation/:conversation_id/events":                         "v1:agent:conversation:streamEvents",
	"GET:/api/v1/agent/conversation/:conversation_id/image-asset":                    "v1:agent:conversation:imageAsset",
	"GET:/api/v1/agent/conversation/:conversation_id/image-assets":                   "v1:agent:conversation:imageAssets",
	"POST:/api/v1/agent/conversation/:conversation_id/messages":                      "v1:agent:conversation:sendMessage",
	"GET:/api/v1/agent/conversation/:conversation_id/metadata":                       "v1:agent:conversation:metadata",
	"POST:/api/v1/agent/conversation/:conversation_id/turn/cancel":                   "v1:agent:conversation:cancelTurn",
	"GET:/api/v1/agent/conversation/:conversation_id/workspace/file":                 "v1:agent:conversation:workspaceFile",
	"GET:/api/v1/agent/conversation/:conversation_id/workspace/files":                "v1:agent:conversation:workspaceFiles",
	"GET:/api/v1/agent/conversation/stats":                                           "v1:agent:conversation:stats",
	"GET:/api/v1/agent/conversation-groups":                                          "v1:agent:conversation:group:list",
	"POST:/api/v1/agent/conversation-groups":                                         "v1:agent:conversation:group:create",
	"DELETE:/api/v1/agent/conversation-groups/:group_id":                             "v1:agent:conversation:group:delete",
	"PATCH:/api/v1/agent/conversation-groups/:group_id":                              "v1:agent:conversation:group:update",
	"POST:/api/v1/agent/conversation-groups/:group_id/archive-conversations":         "v1:agent:conversation:group:archiveConversations",
	"POST:/api/v1/agent/conversation-groups/:group_id/delete-archived-conversations": "v1:agent:conversation:group:deleteArchivedConversations",
	"GET:/api/v1/agent/token/quota":                                                  "v1:agent:token:quotaStatus",
	"GET:/api/v1/agent/token/usage-conversations":                                    "v1:agent:token:usageConversations",
	"GET:/api/v1/agent/token/usage-details":                                          "v1:agent:token:usageDetails",
	"GET:/api/v1/agent/token/usage-trend":                                            "v1:agent:token:usageTrend",
	"POST:/api/v1/auth/code-login":                                                   "v1:auth:codeLogin",
	"GET:/api/v1/auth/getUserInfo":                                                   "v1:auth:getUserInfo",
	"POST:/api/v1/auth/pwd-login":                                                    "v1:auth:pwdLogin",
	"POST:/api/v1/auth/refreshToken":                                                 "v1:auth:refreshToken",
	"POST:/api/v1/auth/register":                                                     "v1:auth:register",
	"POST:/api/v1/auth/resetPassword":                                                "v1:auth:resetPassword",
	"GET:/api/v1/auth/sendVerificationCode":                                          "v1:auth:sendVerificationCode",
	"GET:/api/v1/home/overview":                                                      "v1:home:homeOverview",
	"POST:/api/v1/manage/agent/auth/api-key":                                         "v1:manage:agent:loginApiKey",
	"POST:/api/v1/manage/agent/auth/chatgpt/start":                                   "v1:manage:agent:startChatGPTLogin",
	"POST:/api/v1/manage/agent/auth/logout":                                          "v1:manage:agent:logout",
	"GET:/api/v1/manage/agent/auth/status":                                           "v1:manage:agent:getAccountStatus",
	"GET:/api/v1/manage/agent/settings":                                              "v1:manage:agent:getSettings",
	"POST:/api/v1/manage/agent/settings":                                             "v1:manage:agent:saveSettings",
	"GET:/api/v1/manage/agent/skills":                                                "v1:manage:agent:listSkills",
	"GET:/api/v1/manage/agent/skills/:skill_name":                                    "v1:manage:agent:skillDetail",
	"POST:/api/v1/manage/agent/skills/:skill_name/delete":                            "v1:manage:agent:deleteSkill",
	"POST:/api/v1/manage/agent/skills/:skill_name/file":                              "v1:manage:agent:updateSkillFile",
	"POST:/api/v1/manage/agent/skills/:skill_name/status":                            "v1:manage:agent:setSkillStatus",
	"POST:/api/v1/manage/agent/skills/upload":                                        "v1:manage:agent:uploadSkill",
	"GET:/api/v1/manage/agent/token-quota/global":                                    "v1:manage:agent:getTokenQuotaGlobal",
	"POST:/api/v1/manage/agent/token-quota/global":                                   "v1:manage:agent:saveTokenQuotaGlobal",
	"DELETE:/api/v1/manage/agent/token-quota/users/:user_uuid":                       "v1:manage:agent:deleteUserTokenQuota",
	"GET:/api/v1/manage/agent/token-quota/users/:user_uuid":                          "v1:manage:agent:getUserTokenQuota",
	"POST:/api/v1/manage/agent/token-quota/users/:user_uuid":                         "v1:manage:agent:saveUserTokenQuota",
	"POST:/api/v1/manage/agent/token-quota/users/:user_uuid/reset":                   "v1:manage:agent:resetUserTokenQuota",
	"GET:/api/v1/manage/agent/characters":                                            "v1:manage:agent:character:list",
	"POST:/api/v1/manage/agent/characters/builtin":                                   "v1:manage:agent:character:create",
	"DELETE:/api/v1/manage/agent/characters/builtin/:character_id":                   "v1:manage:agent:character:delete",
	"PATCH:/api/v1/manage/agent/characters/builtin/:character_id":                    "v1:manage:agent:character:update",
	"GET:/api/v1/manage/email/config":                                                "v1:manage:email:getConfig",
	"POST:/api/v1/manage/email/config":                                               "v1:manage:email:saveConfig",
	"POST:/api/v1/manage/email/test":                                                 "v1:manage:email:testConfig",
	"POST:/api/v1/manage/addMenu":                                                    "v1:manage:menu:add",
	"POST:/api/v1/manage/deleteMenu":                                                 "v1:manage:menu:delete",
	"POST:/api/v1/manage/editMenu":                                                   "v1:manage:menu:edit",
	"GET:/api/v1/manage/getAllPages":                                                 "v1:manage:menu:getAllPages",
	"GET:/api/v1/manage/getMenuList":                                                 "v1:manage:menu:list",
	"GET:/api/v1/manage/getMenuTree":                                                 "v1:manage:menu:tree",
	"POST:/api/v1/manage/addRole":                                                    "v1:manage:role:add",
	"POST:/api/v1/manage/deleteRole":                                                 "v1:manage:role:delete",
	"POST:/api/v1/manage/editRole":                                                   "v1:manage:role:edit",
	"GET:/api/v1/manage/getAllRoles":                                                 "v1:manage:role:getAll",
	"GET:/api/v1/manage/getRoleHome":                                                 "v1:manage:role:getHome",
	"GET:/api/v1/manage/getRoleList":                                                 "v1:manage:role:list",
	"GET:/api/v1/manage/getRoleMenus":                                                "v1:manage:role:getMenus",
	"POST:/api/v1/manage/setRoleMenus":                                               "v1:manage:role:setMenus",
	"POST:/api/v1/manage/updateRoleHome":                                             "v1:manage:role:updateHome",
	"POST:/api/v1/manage/addUser":                                                    "v1:manage:user:add",
	"POST:/api/v1/manage/deleteUser":                                                 "v1:manage:user:delete",
	"POST:/api/v1/manage/editUser":                                                   "v1:manage:user:edit",
	"GET:/api/v1/manage/getUserList":                                                 "v1:manage:user:list",
	"GET:/api/v1/plugin/admin-locales":                                               "v1:plugin:locale:get",
	"GET:/api/v1/route/getConstantRoutes":                                            "v1:route:getConstantRoutes",
	"GET:/api/v1/route/getUserRoutes":                                                "v1:route:getUserRoutes",
	"GET:/api/v1/route/isRouteExist":                                                 "v1:route:isRouteExist",
	"GET:/api/version":                                                               "version:version",
}

var (
	MST  map[string]*search.Tree
	once sync.Once
)

func Route2Code(r *http.Request) string {
	once.Do(func() {
		RegisterRoute2Code(RoutesCodesMap)
	})
	if tree, ok := MST[strings.ToUpper(r.Method)]; ok {
		if result, ok := tree.Search(path.Clean(r.URL.Path)); ok {
			return result.Item.(string)
		}
	}

	return "unknown"
}

func RegisterRoute2Code(maps map[string]string) {
	if MST == nil {
		MST = make(map[string]*search.Tree)
	}
	for k, v := range maps {
		if splits := strings.Split(k, ":"); len(splits) >= 2 {
			if _, ok := MST[splits[0]]; ok {
				logx.Must(MST[splits[0]].Add(path.Clean(strings.Join(splits[1:], ":")), v))
			} else {
				tree := search.NewTree()
				logx.Must(tree.Add(strings.Join(splits[1:], ":"), v))
				MST[splits[0]] = tree
			}
		}
	}
}
