// Code generated by jzero. DO NOT EDIT.

package handler

import (
	"net/http"
	"path"
	"strings"
	"sync"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/search"
)

var RoutesCodesMap = map[string]string{
	"GET:/swagger":                                            "swagger:swagger",
	"POST:/api/v1/auth/code-login":                            "v1:auth:codeLogin",
	"GET:/api/v1/auth/getUserInfo":                            "v1:auth:getUserInfo",
	"POST:/api/v1/auth/pwd-login":                             "v1:auth:pwdLogin",
	"POST:/api/v1/auth/refreshToken":                          "v1:auth:refreshToken",
	"POST:/api/v1/auth/register":                              "v1:auth:register",
	"POST:/api/v1/auth/resetPassword":                         "v1:auth:resetPassword",
	"GET:/api/v1/auth/sendVerificationCode":                   "v1:auth:sendVerificationCode",
	"GET:/api/v1/conversations":                               "v1:conversation:list",
	"POST:/api/v1/conversations":                              "v1:conversation:create",
	"DELETE:/api/v1/conversations/:conversation_id":           "v1:conversation:delete",
	"GET:/api/v1/conversations/:conversation_id":              "v1:conversation:get",
	"PATCH:/api/v1/conversations/:conversation_id":            "v1:conversation:update",
	"GET:/api/v1/conversations/:conversation_id/events":       "v1:conversation:streamEvents",
	"POST:/api/v1/conversations/:conversation_id/messages":    "v1:conversation:sendMessage",
	"POST:/api/v1/conversations/:conversation_id/turn/cancel": "v1:conversation:cancelTurn",
	"GET:/api/v1/conversation-groups":                         "v1:conversation:group:list",
	"POST:/api/v1/conversation-groups":                        "v1:conversation:group:create",
	"DELETE:/api/v1/conversation-groups/:group_id":            "v1:conversation:group:delete",
	"PATCH:/api/v1/conversation-groups/:group_id":             "v1:conversation:group:update",
	"POST:/api/v1/conversation-groups/:group_id/archive-conversations": "v1:conversation:group:archiveConversations",
	"POST:/api/v1/conversation-groups/:group_id/delete-archived-conversations": "v1:conversation:group:deleteArchivedConversations",
	"POST:/api/v1/manage/addMenu":                             "v1:manage:menu:add",
	"POST:/api/v1/manage/deleteMenu":                          "v1:manage:menu:delete",
	"POST:/api/v1/manage/editMenu":                            "v1:manage:menu:edit",
	"GET:/api/v1/manage/getAllPages":                          "v1:manage:menu:getAllPages",
	"GET:/api/v1/manage/getMenuList":                          "v1:manage:menu:list",
	"GET:/api/v1/manage/getMenuTree":                          "v1:manage:menu:tree",
	"POST:/api/v1/manage/addRole":                             "v1:manage:role:add",
	"POST:/api/v1/manage/deleteRole":                          "v1:manage:role:delete",
	"POST:/api/v1/manage/editRole":                            "v1:manage:role:edit",
	"GET:/api/v1/manage/getAllRoles":                          "v1:manage:role:getAll",
	"GET:/api/v1/manage/getRoleHome":                          "v1:manage:role:getHome",
	"GET:/api/v1/manage/getRoleList":                          "v1:manage:role:list",
	"GET:/api/v1/manage/getRoleMenus":                         "v1:manage:role:getMenus",
	"POST:/api/v1/manage/setRoleMenus":                        "v1:manage:role:setMenus",
	"POST:/api/v1/manage/updateRoleHome":                      "v1:manage:role:updateHome",
	"POST:/api/v1/manage/addUser":                             "v1:manage:user:add",
	"POST:/api/v1/manage/deleteUser":                          "v1:manage:user:delete",
	"POST:/api/v1/manage/editUser":                            "v1:manage:user:edit",
	"GET:/api/v1/manage/getUserList":                          "v1:manage:user:list",
	"GET:/api/v1/route/getConstantRoutes":                     "v1:route:getConstantRoutes",
	"GET:/api/v1/route/getUserRoutes":                         "v1:route:getUserRoutes",
	"GET:/api/v1/route/isRouteExist":                          "v1:route:isRouteExist",
	"GET:/api/version":                                        "version:version",
}

var (
	MST  map[string]*search.Tree
	once sync.Once
)

func Route2Code(r *http.Request) string {
	once.Do(func() {
		RegisterRoute2Code(RoutesCodesMap)
	})
	if tree, ok := MST[strings.ToUpper(r.Method)]; ok {
		if result, ok := tree.Search(path.Clean(r.URL.Path)); ok {
			return result.Item.(string)
		}
	}

	return "unknown"
}

func RegisterRoute2Code(maps map[string]string) {
	if MST == nil {
		MST = make(map[string]*search.Tree)
	}
	for k, v := range maps {
		if splits := strings.Split(k, ":"); len(splits) >= 2 {
			if _, ok := MST[splits[0]]; ok {
				logx.Must(MST[splits[0]].Add(path.Clean(strings.Join(splits[1:], ":")), v))
			} else {
				tree := search.NewTree()
				logx.Must(tree.Add(strings.Join(splits[1:], ":"), v))
				MST[splits[0]] = tree
			}
		}
	}
}
