services:
  server:
    build:
      context: ../../server
    restart: always
    container_name: agentrazor-server
    privileged: true
    depends_on:
      - postgres
    volumes:
      - ./server/data:/dist/data
      - ./server/logs:/dist/logs
    environment:
      - TZ=Asia/Shanghai
      - DRIVER_NAME=pgx
      - DATASOURCE=postgres://root:123456@postgres:5432/agentrazor
      - REDIS_HOST=redis:6379
  web:
    build:
      context: ../../web
    restart: always
    container_name: agentrazor-web
    depends_on:
      - server
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
      - VITE_SERVICE_BASE_URL=http://127.0.0.1
    ports:
      - "8443:80"
  agent:
    build:
      context: ../../agent
    restart: always
    container_name: agentrazor-agent
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
  postgres:
    image: postgres
    restart: always
    container_name: agentrazor-postgres
    environment:
      TZ: Asia/Shanghai
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: agentrazor
    volumes:
      - ./postgres/data:/var/lib/postgresql
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    restart: always
    container_name: agentrazor-redis
    ports:
      - "6379:6379"
