name: agent-web

on:
  push:
    branches:
      - main
    paths:
      - 'agent/**'
      - '.github/workflows/agent.yaml'
  pull_request:
    paths:
      - 'agent/**'
      - '.github/workflows/agent.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: agent/pnpm-lock.yaml

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2

      - name: Install
        working-directory: agent
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        working-directory: agent
        run: pnpm typecheck

      - name: Build
        working-directory: agent
        run: pnpm build:test
