name: web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yaml'

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: web/pnpm-lock.yaml

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Build web
        run: |-
          cd web
          pnpm install --frozen-lockfile
          pnpm typecheck
          VITE_SERVICE_BASE_URL=https://api.agentrazor-admin-server.jaronnie.com pnpm build
          VITE_SERVICE_BASE_URL=https://api.agentrazor-admin-server.jaronnie.com pnpm build --outDir fc3-dist
          cd ..